/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser.
 * Use it to get access to models, enums, and input types.
 *
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser';
export { Prisma };
export * as $Enums from './enums';
export * from './enums';
/**
 * Model Answer
 *
 */
export type Answer = Prisma.AnswerModel;
/**
 * Model Company
 *
 */
export type Company = Prisma.CompanyModel;
/**
 * Model DimensionCategory
 *
 */
export type DimensionCategory = Prisma.DimensionCategoryModel;
/**
 * Model DimensionIndex
 *
 */
export type DimensionIndex = Prisma.DimensionIndexModel;
/**
 * Model ExperienceDimension
 *
 */
export type ExperienceDimension = Prisma.ExperienceDimensionModel;
/**
 * Model Experience
 *
 */
export type Experience = Prisma.ExperienceModel;
/**
 * Model PersonalityType
 *
 */
export type PersonalityType = Prisma.PersonalityTypeModel;
/**
 * Model Profile
 *
 */
export type Profile = Prisma.ProfileModel;
/**
 * Model Proposal
 *
 */
export type Proposal = Prisma.ProposalModel;
/**
 * Model Provider
 *
 */
export type Provider = Prisma.ProviderModel;
/**
 * Model QuestionDimension
 *
 */
export type QuestionDimension = Prisma.QuestionDimensionModel;
/**
 * Model QuestionOption
 *
 */
export type QuestionOption = Prisma.QuestionOptionModel;
/**
 * Model Question
 *
 */
export type Question = Prisma.QuestionModel;
/**
 * Model RequestPreference
 *
 */
export type RequestPreference = Prisma.RequestPreferenceModel;
/**
 * Model Request
 *
 */
export type Request = Prisma.RequestModel;
/**
 * Model ResponseScore
 *
 */
export type ResponseScore = Prisma.ResponseScoreModel;
/**
 * Model Response
 *
 */
export type Response = Prisma.ResponseModel;
/**
 * Model TeamAggregate
 *
 */
export type TeamAggregate = Prisma.TeamAggregateModel;
/**
 * Model TeamMate
 *
 */
export type TeamMate = Prisma.TeamMateModel;
/**
 * Model TeamVector
 *
 */
export type TeamVector = Prisma.TeamVectorModel;
/**
 * Model Team
 *
 */
export type Team = Prisma.TeamModel;
/**
 * Model UserVector
 *
 */
export type UserVector = Prisma.UserVectorModel;
/**
 * Model User
 *
 */
export type User = Prisma.UserModel;
