sonar.projectKey=felix-li078_popcolab
sonar.organization=felix-li078
sonar.token=3b7eb66b2177a7fb862faad0b4844ca5c9037a19
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.exclusions=node_modules/**,.next/**,coverage/**
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.json