/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `DimensionIndex` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client';
import type * as $Enums from '../enums';
import type * as Prisma from '../internal/prismaNamespace';

/**
 * Model DimensionIndex
 *
 */
export type DimensionIndexModel =
  runtime.Types.Result.DefaultSelection<Prisma.$DimensionIndexPayload>;

export type AggregateDimensionIndex = {
  _count: DimensionIndexCountAggregateOutputType | null;
  _avg: DimensionIndexAvgAggregateOutputType | null;
  _sum: DimensionIndexSumAggregateOutputType | null;
  _min: DimensionIndexMinAggregateOutputType | null;
  _max: DimensionIndexMaxAggregateOutputType | null;
};

export type DimensionIndexAvgAggregateOutputType = {
  id: number | null;
  category_id: number | null;
  scale_min: number | null;
  scale_max: number | null;
};

export type DimensionIndexSumAggregateOutputType = {
  id: number | null;
  category_id: number | null;
  scale_min: number | null;
  scale_max: number | null;
};

export type DimensionIndexMinAggregateOutputType = {
  id: number | null;
  index_key: string | null;
  category_id: number | null;
  index_name: string | null;
  data_type: string | null;
  hard_filter: boolean | null;
  scale_min: number | null;
  scale_max: number | null;
  created_at: Date | null;
  updated_at: Date | null;
};

export type DimensionIndexMaxAggregateOutputType = {
  id: number | null;
  index_key: string | null;
  category_id: number | null;
  index_name: string | null;
  data_type: string | null;
  hard_filter: boolean | null;
  scale_min: number | null;
  scale_max: number | null;
  created_at: Date | null;
  updated_at: Date | null;
};

export type DimensionIndexCountAggregateOutputType = {
  id: number;
  index_key: number;
  category_id: number;
  index_name: number;
  data_type: number;
  hard_filter: number;
  scale_min: number;
  scale_max: number;
  created_at: number;
  updated_at: number;
  _all: number;
};

export type DimensionIndexAvgAggregateInputType = {
  id?: true;
  category_id?: true;
  scale_min?: true;
  scale_max?: true;
};

export type DimensionIndexSumAggregateInputType = {
  id?: true;
  category_id?: true;
  scale_min?: true;
  scale_max?: true;
};

export type DimensionIndexMinAggregateInputType = {
  id?: true;
  index_key?: true;
  category_id?: true;
  index_name?: true;
  data_type?: true;
  hard_filter?: true;
  scale_min?: true;
  scale_max?: true;
  created_at?: true;
  updated_at?: true;
};

export type DimensionIndexMaxAggregateInputType = {
  id?: true;
  index_key?: true;
  category_id?: true;
  index_name?: true;
  data_type?: true;
  hard_filter?: true;
  scale_min?: true;
  scale_max?: true;
  created_at?: true;
  updated_at?: true;
};

export type DimensionIndexCountAggregateInputType = {
  id?: true;
  index_key?: true;
  category_id?: true;
  index_name?: true;
  data_type?: true;
  hard_filter?: true;
  scale_min?: true;
  scale_max?: true;
  created_at?: true;
  updated_at?: true;
  _all?: true;
};

export type DimensionIndexAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which DimensionIndex to aggregate.
   */
  where?: Prisma.DimensionIndexWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of DimensionIndices to fetch.
   */
  orderBy?:
    | Prisma.DimensionIndexOrderByWithRelationInput
    | Prisma.DimensionIndexOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.DimensionIndexWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` DimensionIndices from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` DimensionIndices.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned DimensionIndices
   **/
  _count?: true | DimensionIndexCountAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: DimensionIndexAvgAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: DimensionIndexSumAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: DimensionIndexMinAggregateInputType;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: DimensionIndexMaxAggregateInputType;
};

export type GetDimensionIndexAggregateType<
  T extends DimensionIndexAggregateArgs,
> = {
  [P in keyof T & keyof AggregateDimensionIndex]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDimensionIndex[P]>
    : Prisma.GetScalarType<T[P], AggregateDimensionIndex[P]>;
};

export type DimensionIndexGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.DimensionIndexWhereInput;
  orderBy?:
    | Prisma.DimensionIndexOrderByWithAggregationInput
    | Prisma.DimensionIndexOrderByWithAggregationInput[];
  by:
    | Prisma.DimensionIndexScalarFieldEnum[]
    | Prisma.DimensionIndexScalarFieldEnum;
  having?: Prisma.DimensionIndexScalarWhereWithAggregatesInput;
  take?: number;
  skip?: number;
  _count?: DimensionIndexCountAggregateInputType | true;
  _avg?: DimensionIndexAvgAggregateInputType;
  _sum?: DimensionIndexSumAggregateInputType;
  _min?: DimensionIndexMinAggregateInputType;
  _max?: DimensionIndexMaxAggregateInputType;
};

export type DimensionIndexGroupByOutputType = {
  id: number;
  index_key: string | null;
  category_id: number;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min: number | null;
  scale_max: number | null;
  created_at: Date;
  updated_at: Date;
  _count: DimensionIndexCountAggregateOutputType | null;
  _avg: DimensionIndexAvgAggregateOutputType | null;
  _sum: DimensionIndexSumAggregateOutputType | null;
  _min: DimensionIndexMinAggregateOutputType | null;
  _max: DimensionIndexMaxAggregateOutputType | null;
};

type GetDimensionIndexGroupByPayload<T extends DimensionIndexGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<DimensionIndexGroupByOutputType, T['by']> & {
        [P in keyof T &
          keyof DimensionIndexGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DimensionIndexGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DimensionIndexGroupByOutputType[P]>;
      }
    >
  >;

export type DimensionIndexWhereInput = {
  AND?: Prisma.DimensionIndexWhereInput | Prisma.DimensionIndexWhereInput[];
  OR?: Prisma.DimensionIndexWhereInput[];
  NOT?: Prisma.DimensionIndexWhereInput | Prisma.DimensionIndexWhereInput[];
  id?: Prisma.IntFilter<'DimensionIndex'> | number;
  index_key?: Prisma.StringNullableFilter<'DimensionIndex'> | string | null;
  category_id?: Prisma.IntFilter<'DimensionIndex'> | number;
  index_name?: Prisma.StringFilter<'DimensionIndex'> | string;
  data_type?: Prisma.StringFilter<'DimensionIndex'> | string;
  hard_filter?: Prisma.BoolFilter<'DimensionIndex'> | boolean;
  scale_min?: Prisma.IntNullableFilter<'DimensionIndex'> | number | null;
  scale_max?: Prisma.IntNullableFilter<'DimensionIndex'> | number | null;
  created_at?: Prisma.DateTimeFilter<'DimensionIndex'> | Date | string;
  updated_at?: Prisma.DateTimeFilter<'DimensionIndex'> | Date | string;
  category?: Prisma.XOR<
    Prisma.DimensionCategoryScalarRelationFilter,
    Prisma.DimensionCategoryWhereInput
  >;
  experience_dimensions?: Prisma.ExperienceDimensionListRelationFilter;
  question_dimensions?: Prisma.QuestionDimensionListRelationFilter;
  request_preferences?: Prisma.RequestPreferenceListRelationFilter;
};

export type DimensionIndexOrderByWithRelationInput = {
  id?: Prisma.SortOrder;
  index_key?: Prisma.SortOrderInput | Prisma.SortOrder;
  category_id?: Prisma.SortOrder;
  index_name?: Prisma.SortOrder;
  data_type?: Prisma.SortOrder;
  hard_filter?: Prisma.SortOrder;
  scale_min?: Prisma.SortOrderInput | Prisma.SortOrder;
  scale_max?: Prisma.SortOrderInput | Prisma.SortOrder;
  created_at?: Prisma.SortOrder;
  updated_at?: Prisma.SortOrder;
  category?: Prisma.DimensionCategoryOrderByWithRelationInput;
  experience_dimensions?: Prisma.ExperienceDimensionOrderByRelationAggregateInput;
  question_dimensions?: Prisma.QuestionDimensionOrderByRelationAggregateInput;
  request_preferences?: Prisma.RequestPreferenceOrderByRelationAggregateInput;
};

export type DimensionIndexWhereUniqueInput = Prisma.AtLeast<
  {
    id?: number;
    AND?: Prisma.DimensionIndexWhereInput | Prisma.DimensionIndexWhereInput[];
    OR?: Prisma.DimensionIndexWhereInput[];
    NOT?: Prisma.DimensionIndexWhereInput | Prisma.DimensionIndexWhereInput[];
    index_key?: Prisma.StringNullableFilter<'DimensionIndex'> | string | null;
    category_id?: Prisma.IntFilter<'DimensionIndex'> | number;
    index_name?: Prisma.StringFilter<'DimensionIndex'> | string;
    data_type?: Prisma.StringFilter<'DimensionIndex'> | string;
    hard_filter?: Prisma.BoolFilter<'DimensionIndex'> | boolean;
    scale_min?: Prisma.IntNullableFilter<'DimensionIndex'> | number | null;
    scale_max?: Prisma.IntNullableFilter<'DimensionIndex'> | number | null;
    created_at?: Prisma.DateTimeFilter<'DimensionIndex'> | Date | string;
    updated_at?: Prisma.DateTimeFilter<'DimensionIndex'> | Date | string;
    category?: Prisma.XOR<
      Prisma.DimensionCategoryScalarRelationFilter,
      Prisma.DimensionCategoryWhereInput
    >;
    experience_dimensions?: Prisma.ExperienceDimensionListRelationFilter;
    question_dimensions?: Prisma.QuestionDimensionListRelationFilter;
    request_preferences?: Prisma.RequestPreferenceListRelationFilter;
  },
  'id'
>;

export type DimensionIndexOrderByWithAggregationInput = {
  id?: Prisma.SortOrder;
  index_key?: Prisma.SortOrderInput | Prisma.SortOrder;
  category_id?: Prisma.SortOrder;
  index_name?: Prisma.SortOrder;
  data_type?: Prisma.SortOrder;
  hard_filter?: Prisma.SortOrder;
  scale_min?: Prisma.SortOrderInput | Prisma.SortOrder;
  scale_max?: Prisma.SortOrderInput | Prisma.SortOrder;
  created_at?: Prisma.SortOrder;
  updated_at?: Prisma.SortOrder;
  _count?: Prisma.DimensionIndexCountOrderByAggregateInput;
  _avg?: Prisma.DimensionIndexAvgOrderByAggregateInput;
  _max?: Prisma.DimensionIndexMaxOrderByAggregateInput;
  _min?: Prisma.DimensionIndexMinOrderByAggregateInput;
  _sum?: Prisma.DimensionIndexSumOrderByAggregateInput;
};

export type DimensionIndexScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.DimensionIndexScalarWhereWithAggregatesInput
    | Prisma.DimensionIndexScalarWhereWithAggregatesInput[];
  OR?: Prisma.DimensionIndexScalarWhereWithAggregatesInput[];
  NOT?:
    | Prisma.DimensionIndexScalarWhereWithAggregatesInput
    | Prisma.DimensionIndexScalarWhereWithAggregatesInput[];
  id?: Prisma.IntWithAggregatesFilter<'DimensionIndex'> | number;
  index_key?:
    | Prisma.StringNullableWithAggregatesFilter<'DimensionIndex'>
    | string
    | null;
  category_id?: Prisma.IntWithAggregatesFilter<'DimensionIndex'> | number;
  index_name?: Prisma.StringWithAggregatesFilter<'DimensionIndex'> | string;
  data_type?: Prisma.StringWithAggregatesFilter<'DimensionIndex'> | string;
  hard_filter?: Prisma.BoolWithAggregatesFilter<'DimensionIndex'> | boolean;
  scale_min?:
    | Prisma.IntNullableWithAggregatesFilter<'DimensionIndex'>
    | number
    | null;
  scale_max?:
    | Prisma.IntNullableWithAggregatesFilter<'DimensionIndex'>
    | number
    | null;
  created_at?:
    | Prisma.DateTimeWithAggregatesFilter<'DimensionIndex'>
    | Date
    | string;
  updated_at?:
    | Prisma.DateTimeWithAggregatesFilter<'DimensionIndex'>
    | Date
    | string;
};

export type DimensionIndexCreateInput = {
  index_key?: string | null;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
  category: Prisma.DimensionCategoryCreateNestedOneWithoutIndexesInput;
  experience_dimensions?: Prisma.ExperienceDimensionCreateNestedManyWithoutDimension_indexInput;
  question_dimensions?: Prisma.QuestionDimensionCreateNestedManyWithoutDimensionInput;
  request_preferences?: Prisma.RequestPreferenceCreateNestedManyWithoutDimension_indexInput;
};

export type DimensionIndexUncheckedCreateInput = {
  id?: number;
  index_key?: string | null;
  category_id: number;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
  experience_dimensions?: Prisma.ExperienceDimensionUncheckedCreateNestedManyWithoutDimension_indexInput;
  question_dimensions?: Prisma.QuestionDimensionUncheckedCreateNestedManyWithoutDimensionInput;
  request_preferences?: Prisma.RequestPreferenceUncheckedCreateNestedManyWithoutDimension_indexInput;
};

export type DimensionIndexUpdateInput = {
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  category?: Prisma.DimensionCategoryUpdateOneRequiredWithoutIndexesNestedInput;
  experience_dimensions?: Prisma.ExperienceDimensionUpdateManyWithoutDimension_indexNestedInput;
  question_dimensions?: Prisma.QuestionDimensionUpdateManyWithoutDimensionNestedInput;
  request_preferences?: Prisma.RequestPreferenceUpdateManyWithoutDimension_indexNestedInput;
};

export type DimensionIndexUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  category_id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  experience_dimensions?: Prisma.ExperienceDimensionUncheckedUpdateManyWithoutDimension_indexNestedInput;
  question_dimensions?: Prisma.QuestionDimensionUncheckedUpdateManyWithoutDimensionNestedInput;
  request_preferences?: Prisma.RequestPreferenceUncheckedUpdateManyWithoutDimension_indexNestedInput;
};

export type DimensionIndexCreateManyInput = {
  id?: number;
  index_key?: string | null;
  category_id: number;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
};

export type DimensionIndexUpdateManyMutationInput = {
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type DimensionIndexUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  category_id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

export type DimensionIndexListRelationFilter = {
  every?: Prisma.DimensionIndexWhereInput;
  some?: Prisma.DimensionIndexWhereInput;
  none?: Prisma.DimensionIndexWhereInput;
};

export type DimensionIndexOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder;
};

export type DimensionIndexCountOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  index_key?: Prisma.SortOrder;
  category_id?: Prisma.SortOrder;
  index_name?: Prisma.SortOrder;
  data_type?: Prisma.SortOrder;
  hard_filter?: Prisma.SortOrder;
  scale_min?: Prisma.SortOrder;
  scale_max?: Prisma.SortOrder;
  created_at?: Prisma.SortOrder;
  updated_at?: Prisma.SortOrder;
};

export type DimensionIndexAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  category_id?: Prisma.SortOrder;
  scale_min?: Prisma.SortOrder;
  scale_max?: Prisma.SortOrder;
};

export type DimensionIndexMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  index_key?: Prisma.SortOrder;
  category_id?: Prisma.SortOrder;
  index_name?: Prisma.SortOrder;
  data_type?: Prisma.SortOrder;
  hard_filter?: Prisma.SortOrder;
  scale_min?: Prisma.SortOrder;
  scale_max?: Prisma.SortOrder;
  created_at?: Prisma.SortOrder;
  updated_at?: Prisma.SortOrder;
};

export type DimensionIndexMinOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  index_key?: Prisma.SortOrder;
  category_id?: Prisma.SortOrder;
  index_name?: Prisma.SortOrder;
  data_type?: Prisma.SortOrder;
  hard_filter?: Prisma.SortOrder;
  scale_min?: Prisma.SortOrder;
  scale_max?: Prisma.SortOrder;
  created_at?: Prisma.SortOrder;
  updated_at?: Prisma.SortOrder;
};

export type DimensionIndexSumOrderByAggregateInput = {
  id?: Prisma.SortOrder;
  category_id?: Prisma.SortOrder;
  scale_min?: Prisma.SortOrder;
  scale_max?: Prisma.SortOrder;
};

export type DimensionIndexScalarRelationFilter = {
  is?: Prisma.DimensionIndexWhereInput;
  isNot?: Prisma.DimensionIndexWhereInput;
};

export type DimensionIndexCreateNestedManyWithoutCategoryInput = {
  create?:
    | Prisma.XOR<
        Prisma.DimensionIndexCreateWithoutCategoryInput,
        Prisma.DimensionIndexUncheckedCreateWithoutCategoryInput
      >
    | Prisma.DimensionIndexCreateWithoutCategoryInput[]
    | Prisma.DimensionIndexUncheckedCreateWithoutCategoryInput[];
  connectOrCreate?:
    | Prisma.DimensionIndexCreateOrConnectWithoutCategoryInput
    | Prisma.DimensionIndexCreateOrConnectWithoutCategoryInput[];
  createMany?: Prisma.DimensionIndexCreateManyCategoryInputEnvelope;
  connect?:
    | Prisma.DimensionIndexWhereUniqueInput
    | Prisma.DimensionIndexWhereUniqueInput[];
};

export type DimensionIndexUncheckedCreateNestedManyWithoutCategoryInput = {
  create?:
    | Prisma.XOR<
        Prisma.DimensionIndexCreateWithoutCategoryInput,
        Prisma.DimensionIndexUncheckedCreateWithoutCategoryInput
      >
    | Prisma.DimensionIndexCreateWithoutCategoryInput[]
    | Prisma.DimensionIndexUncheckedCreateWithoutCategoryInput[];
  connectOrCreate?:
    | Prisma.DimensionIndexCreateOrConnectWithoutCategoryInput
    | Prisma.DimensionIndexCreateOrConnectWithoutCategoryInput[];
  createMany?: Prisma.DimensionIndexCreateManyCategoryInputEnvelope;
  connect?:
    | Prisma.DimensionIndexWhereUniqueInput
    | Prisma.DimensionIndexWhereUniqueInput[];
};

export type DimensionIndexUpdateManyWithoutCategoryNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.DimensionIndexCreateWithoutCategoryInput,
        Prisma.DimensionIndexUncheckedCreateWithoutCategoryInput
      >
    | Prisma.DimensionIndexCreateWithoutCategoryInput[]
    | Prisma.DimensionIndexUncheckedCreateWithoutCategoryInput[];
  connectOrCreate?:
    | Prisma.DimensionIndexCreateOrConnectWithoutCategoryInput
    | Prisma.DimensionIndexCreateOrConnectWithoutCategoryInput[];
  upsert?:
    | Prisma.DimensionIndexUpsertWithWhereUniqueWithoutCategoryInput
    | Prisma.DimensionIndexUpsertWithWhereUniqueWithoutCategoryInput[];
  createMany?: Prisma.DimensionIndexCreateManyCategoryInputEnvelope;
  set?:
    | Prisma.DimensionIndexWhereUniqueInput
    | Prisma.DimensionIndexWhereUniqueInput[];
  disconnect?:
    | Prisma.DimensionIndexWhereUniqueInput
    | Prisma.DimensionIndexWhereUniqueInput[];
  delete?:
    | Prisma.DimensionIndexWhereUniqueInput
    | Prisma.DimensionIndexWhereUniqueInput[];
  connect?:
    | Prisma.DimensionIndexWhereUniqueInput
    | Prisma.DimensionIndexWhereUniqueInput[];
  update?:
    | Prisma.DimensionIndexUpdateWithWhereUniqueWithoutCategoryInput
    | Prisma.DimensionIndexUpdateWithWhereUniqueWithoutCategoryInput[];
  updateMany?:
    | Prisma.DimensionIndexUpdateManyWithWhereWithoutCategoryInput
    | Prisma.DimensionIndexUpdateManyWithWhereWithoutCategoryInput[];
  deleteMany?:
    | Prisma.DimensionIndexScalarWhereInput
    | Prisma.DimensionIndexScalarWhereInput[];
};

export type DimensionIndexUncheckedUpdateManyWithoutCategoryNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.DimensionIndexCreateWithoutCategoryInput,
        Prisma.DimensionIndexUncheckedCreateWithoutCategoryInput
      >
    | Prisma.DimensionIndexCreateWithoutCategoryInput[]
    | Prisma.DimensionIndexUncheckedCreateWithoutCategoryInput[];
  connectOrCreate?:
    | Prisma.DimensionIndexCreateOrConnectWithoutCategoryInput
    | Prisma.DimensionIndexCreateOrConnectWithoutCategoryInput[];
  upsert?:
    | Prisma.DimensionIndexUpsertWithWhereUniqueWithoutCategoryInput
    | Prisma.DimensionIndexUpsertWithWhereUniqueWithoutCategoryInput[];
  createMany?: Prisma.DimensionIndexCreateManyCategoryInputEnvelope;
  set?:
    | Prisma.DimensionIndexWhereUniqueInput
    | Prisma.DimensionIndexWhereUniqueInput[];
  disconnect?:
    | Prisma.DimensionIndexWhereUniqueInput
    | Prisma.DimensionIndexWhereUniqueInput[];
  delete?:
    | Prisma.DimensionIndexWhereUniqueInput
    | Prisma.DimensionIndexWhereUniqueInput[];
  connect?:
    | Prisma.DimensionIndexWhereUniqueInput
    | Prisma.DimensionIndexWhereUniqueInput[];
  update?:
    | Prisma.DimensionIndexUpdateWithWhereUniqueWithoutCategoryInput
    | Prisma.DimensionIndexUpdateWithWhereUniqueWithoutCategoryInput[];
  updateMany?:
    | Prisma.DimensionIndexUpdateManyWithWhereWithoutCategoryInput
    | Prisma.DimensionIndexUpdateManyWithWhereWithoutCategoryInput[];
  deleteMany?:
    | Prisma.DimensionIndexScalarWhereInput
    | Prisma.DimensionIndexScalarWhereInput[];
};

export type BoolFieldUpdateOperationsInput = {
  set?: boolean;
};

export type DimensionIndexCreateNestedOneWithoutExperience_dimensionsInput = {
  create?: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutExperience_dimensionsInput,
    Prisma.DimensionIndexUncheckedCreateWithoutExperience_dimensionsInput
  >;
  connectOrCreate?: Prisma.DimensionIndexCreateOrConnectWithoutExperience_dimensionsInput;
  connect?: Prisma.DimensionIndexWhereUniqueInput;
};

export type DimensionIndexUpdateOneRequiredWithoutExperience_dimensionsNestedInput =
  {
    create?: Prisma.XOR<
      Prisma.DimensionIndexCreateWithoutExperience_dimensionsInput,
      Prisma.DimensionIndexUncheckedCreateWithoutExperience_dimensionsInput
    >;
    connectOrCreate?: Prisma.DimensionIndexCreateOrConnectWithoutExperience_dimensionsInput;
    upsert?: Prisma.DimensionIndexUpsertWithoutExperience_dimensionsInput;
    connect?: Prisma.DimensionIndexWhereUniqueInput;
    update?: Prisma.XOR<
      Prisma.XOR<
        Prisma.DimensionIndexUpdateToOneWithWhereWithoutExperience_dimensionsInput,
        Prisma.DimensionIndexUpdateWithoutExperience_dimensionsInput
      >,
      Prisma.DimensionIndexUncheckedUpdateWithoutExperience_dimensionsInput
    >;
  };

export type DimensionIndexCreateNestedOneWithoutQuestion_dimensionsInput = {
  create?: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutQuestion_dimensionsInput,
    Prisma.DimensionIndexUncheckedCreateWithoutQuestion_dimensionsInput
  >;
  connectOrCreate?: Prisma.DimensionIndexCreateOrConnectWithoutQuestion_dimensionsInput;
  connect?: Prisma.DimensionIndexWhereUniqueInput;
};

export type DimensionIndexUpdateOneRequiredWithoutQuestion_dimensionsNestedInput =
  {
    create?: Prisma.XOR<
      Prisma.DimensionIndexCreateWithoutQuestion_dimensionsInput,
      Prisma.DimensionIndexUncheckedCreateWithoutQuestion_dimensionsInput
    >;
    connectOrCreate?: Prisma.DimensionIndexCreateOrConnectWithoutQuestion_dimensionsInput;
    upsert?: Prisma.DimensionIndexUpsertWithoutQuestion_dimensionsInput;
    connect?: Prisma.DimensionIndexWhereUniqueInput;
    update?: Prisma.XOR<
      Prisma.XOR<
        Prisma.DimensionIndexUpdateToOneWithWhereWithoutQuestion_dimensionsInput,
        Prisma.DimensionIndexUpdateWithoutQuestion_dimensionsInput
      >,
      Prisma.DimensionIndexUncheckedUpdateWithoutQuestion_dimensionsInput
    >;
  };

export type DimensionIndexCreateNestedOneWithoutRequest_preferencesInput = {
  create?: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutRequest_preferencesInput,
    Prisma.DimensionIndexUncheckedCreateWithoutRequest_preferencesInput
  >;
  connectOrCreate?: Prisma.DimensionIndexCreateOrConnectWithoutRequest_preferencesInput;
  connect?: Prisma.DimensionIndexWhereUniqueInput;
};

export type DimensionIndexUpdateOneRequiredWithoutRequest_preferencesNestedInput =
  {
    create?: Prisma.XOR<
      Prisma.DimensionIndexCreateWithoutRequest_preferencesInput,
      Prisma.DimensionIndexUncheckedCreateWithoutRequest_preferencesInput
    >;
    connectOrCreate?: Prisma.DimensionIndexCreateOrConnectWithoutRequest_preferencesInput;
    upsert?: Prisma.DimensionIndexUpsertWithoutRequest_preferencesInput;
    connect?: Prisma.DimensionIndexWhereUniqueInput;
    update?: Prisma.XOR<
      Prisma.XOR<
        Prisma.DimensionIndexUpdateToOneWithWhereWithoutRequest_preferencesInput,
        Prisma.DimensionIndexUpdateWithoutRequest_preferencesInput
      >,
      Prisma.DimensionIndexUncheckedUpdateWithoutRequest_preferencesInput
    >;
  };

export type DimensionIndexCreateWithoutCategoryInput = {
  index_key?: string | null;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
  experience_dimensions?: Prisma.ExperienceDimensionCreateNestedManyWithoutDimension_indexInput;
  question_dimensions?: Prisma.QuestionDimensionCreateNestedManyWithoutDimensionInput;
  request_preferences?: Prisma.RequestPreferenceCreateNestedManyWithoutDimension_indexInput;
};

export type DimensionIndexUncheckedCreateWithoutCategoryInput = {
  id?: number;
  index_key?: string | null;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
  experience_dimensions?: Prisma.ExperienceDimensionUncheckedCreateNestedManyWithoutDimension_indexInput;
  question_dimensions?: Prisma.QuestionDimensionUncheckedCreateNestedManyWithoutDimensionInput;
  request_preferences?: Prisma.RequestPreferenceUncheckedCreateNestedManyWithoutDimension_indexInput;
};

export type DimensionIndexCreateOrConnectWithoutCategoryInput = {
  where: Prisma.DimensionIndexWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutCategoryInput,
    Prisma.DimensionIndexUncheckedCreateWithoutCategoryInput
  >;
};

export type DimensionIndexCreateManyCategoryInputEnvelope = {
  data:
    | Prisma.DimensionIndexCreateManyCategoryInput
    | Prisma.DimensionIndexCreateManyCategoryInput[];
  skipDuplicates?: boolean;
};

export type DimensionIndexUpsertWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.DimensionIndexWhereUniqueInput;
  update: Prisma.XOR<
    Prisma.DimensionIndexUpdateWithoutCategoryInput,
    Prisma.DimensionIndexUncheckedUpdateWithoutCategoryInput
  >;
  create: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutCategoryInput,
    Prisma.DimensionIndexUncheckedCreateWithoutCategoryInput
  >;
};

export type DimensionIndexUpdateWithWhereUniqueWithoutCategoryInput = {
  where: Prisma.DimensionIndexWhereUniqueInput;
  data: Prisma.XOR<
    Prisma.DimensionIndexUpdateWithoutCategoryInput,
    Prisma.DimensionIndexUncheckedUpdateWithoutCategoryInput
  >;
};

export type DimensionIndexUpdateManyWithWhereWithoutCategoryInput = {
  where: Prisma.DimensionIndexScalarWhereInput;
  data: Prisma.XOR<
    Prisma.DimensionIndexUpdateManyMutationInput,
    Prisma.DimensionIndexUncheckedUpdateManyWithoutCategoryInput
  >;
};

export type DimensionIndexScalarWhereInput = {
  AND?:
    | Prisma.DimensionIndexScalarWhereInput
    | Prisma.DimensionIndexScalarWhereInput[];
  OR?: Prisma.DimensionIndexScalarWhereInput[];
  NOT?:
    | Prisma.DimensionIndexScalarWhereInput
    | Prisma.DimensionIndexScalarWhereInput[];
  id?: Prisma.IntFilter<'DimensionIndex'> | number;
  index_key?: Prisma.StringNullableFilter<'DimensionIndex'> | string | null;
  category_id?: Prisma.IntFilter<'DimensionIndex'> | number;
  index_name?: Prisma.StringFilter<'DimensionIndex'> | string;
  data_type?: Prisma.StringFilter<'DimensionIndex'> | string;
  hard_filter?: Prisma.BoolFilter<'DimensionIndex'> | boolean;
  scale_min?: Prisma.IntNullableFilter<'DimensionIndex'> | number | null;
  scale_max?: Prisma.IntNullableFilter<'DimensionIndex'> | number | null;
  created_at?: Prisma.DateTimeFilter<'DimensionIndex'> | Date | string;
  updated_at?: Prisma.DateTimeFilter<'DimensionIndex'> | Date | string;
};

export type DimensionIndexCreateWithoutExperience_dimensionsInput = {
  index_key?: string | null;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
  category: Prisma.DimensionCategoryCreateNestedOneWithoutIndexesInput;
  question_dimensions?: Prisma.QuestionDimensionCreateNestedManyWithoutDimensionInput;
  request_preferences?: Prisma.RequestPreferenceCreateNestedManyWithoutDimension_indexInput;
};

export type DimensionIndexUncheckedCreateWithoutExperience_dimensionsInput = {
  id?: number;
  index_key?: string | null;
  category_id: number;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
  question_dimensions?: Prisma.QuestionDimensionUncheckedCreateNestedManyWithoutDimensionInput;
  request_preferences?: Prisma.RequestPreferenceUncheckedCreateNestedManyWithoutDimension_indexInput;
};

export type DimensionIndexCreateOrConnectWithoutExperience_dimensionsInput = {
  where: Prisma.DimensionIndexWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutExperience_dimensionsInput,
    Prisma.DimensionIndexUncheckedCreateWithoutExperience_dimensionsInput
  >;
};

export type DimensionIndexUpsertWithoutExperience_dimensionsInput = {
  update: Prisma.XOR<
    Prisma.DimensionIndexUpdateWithoutExperience_dimensionsInput,
    Prisma.DimensionIndexUncheckedUpdateWithoutExperience_dimensionsInput
  >;
  create: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutExperience_dimensionsInput,
    Prisma.DimensionIndexUncheckedCreateWithoutExperience_dimensionsInput
  >;
  where?: Prisma.DimensionIndexWhereInput;
};

export type DimensionIndexUpdateToOneWithWhereWithoutExperience_dimensionsInput =
  {
    where?: Prisma.DimensionIndexWhereInput;
    data: Prisma.XOR<
      Prisma.DimensionIndexUpdateWithoutExperience_dimensionsInput,
      Prisma.DimensionIndexUncheckedUpdateWithoutExperience_dimensionsInput
    >;
  };

export type DimensionIndexUpdateWithoutExperience_dimensionsInput = {
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  category?: Prisma.DimensionCategoryUpdateOneRequiredWithoutIndexesNestedInput;
  question_dimensions?: Prisma.QuestionDimensionUpdateManyWithoutDimensionNestedInput;
  request_preferences?: Prisma.RequestPreferenceUpdateManyWithoutDimension_indexNestedInput;
};

export type DimensionIndexUncheckedUpdateWithoutExperience_dimensionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  category_id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  question_dimensions?: Prisma.QuestionDimensionUncheckedUpdateManyWithoutDimensionNestedInput;
  request_preferences?: Prisma.RequestPreferenceUncheckedUpdateManyWithoutDimension_indexNestedInput;
};

export type DimensionIndexCreateWithoutQuestion_dimensionsInput = {
  index_key?: string | null;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
  category: Prisma.DimensionCategoryCreateNestedOneWithoutIndexesInput;
  experience_dimensions?: Prisma.ExperienceDimensionCreateNestedManyWithoutDimension_indexInput;
  request_preferences?: Prisma.RequestPreferenceCreateNestedManyWithoutDimension_indexInput;
};

export type DimensionIndexUncheckedCreateWithoutQuestion_dimensionsInput = {
  id?: number;
  index_key?: string | null;
  category_id: number;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
  experience_dimensions?: Prisma.ExperienceDimensionUncheckedCreateNestedManyWithoutDimension_indexInput;
  request_preferences?: Prisma.RequestPreferenceUncheckedCreateNestedManyWithoutDimension_indexInput;
};

export type DimensionIndexCreateOrConnectWithoutQuestion_dimensionsInput = {
  where: Prisma.DimensionIndexWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutQuestion_dimensionsInput,
    Prisma.DimensionIndexUncheckedCreateWithoutQuestion_dimensionsInput
  >;
};

export type DimensionIndexUpsertWithoutQuestion_dimensionsInput = {
  update: Prisma.XOR<
    Prisma.DimensionIndexUpdateWithoutQuestion_dimensionsInput,
    Prisma.DimensionIndexUncheckedUpdateWithoutQuestion_dimensionsInput
  >;
  create: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutQuestion_dimensionsInput,
    Prisma.DimensionIndexUncheckedCreateWithoutQuestion_dimensionsInput
  >;
  where?: Prisma.DimensionIndexWhereInput;
};

export type DimensionIndexUpdateToOneWithWhereWithoutQuestion_dimensionsInput =
  {
    where?: Prisma.DimensionIndexWhereInput;
    data: Prisma.XOR<
      Prisma.DimensionIndexUpdateWithoutQuestion_dimensionsInput,
      Prisma.DimensionIndexUncheckedUpdateWithoutQuestion_dimensionsInput
    >;
  };

export type DimensionIndexUpdateWithoutQuestion_dimensionsInput = {
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  category?: Prisma.DimensionCategoryUpdateOneRequiredWithoutIndexesNestedInput;
  experience_dimensions?: Prisma.ExperienceDimensionUpdateManyWithoutDimension_indexNestedInput;
  request_preferences?: Prisma.RequestPreferenceUpdateManyWithoutDimension_indexNestedInput;
};

export type DimensionIndexUncheckedUpdateWithoutQuestion_dimensionsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  category_id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  experience_dimensions?: Prisma.ExperienceDimensionUncheckedUpdateManyWithoutDimension_indexNestedInput;
  request_preferences?: Prisma.RequestPreferenceUncheckedUpdateManyWithoutDimension_indexNestedInput;
};

export type DimensionIndexCreateWithoutRequest_preferencesInput = {
  index_key?: string | null;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
  category: Prisma.DimensionCategoryCreateNestedOneWithoutIndexesInput;
  experience_dimensions?: Prisma.ExperienceDimensionCreateNestedManyWithoutDimension_indexInput;
  question_dimensions?: Prisma.QuestionDimensionCreateNestedManyWithoutDimensionInput;
};

export type DimensionIndexUncheckedCreateWithoutRequest_preferencesInput = {
  id?: number;
  index_key?: string | null;
  category_id: number;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
  experience_dimensions?: Prisma.ExperienceDimensionUncheckedCreateNestedManyWithoutDimension_indexInput;
  question_dimensions?: Prisma.QuestionDimensionUncheckedCreateNestedManyWithoutDimensionInput;
};

export type DimensionIndexCreateOrConnectWithoutRequest_preferencesInput = {
  where: Prisma.DimensionIndexWhereUniqueInput;
  create: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutRequest_preferencesInput,
    Prisma.DimensionIndexUncheckedCreateWithoutRequest_preferencesInput
  >;
};

export type DimensionIndexUpsertWithoutRequest_preferencesInput = {
  update: Prisma.XOR<
    Prisma.DimensionIndexUpdateWithoutRequest_preferencesInput,
    Prisma.DimensionIndexUncheckedUpdateWithoutRequest_preferencesInput
  >;
  create: Prisma.XOR<
    Prisma.DimensionIndexCreateWithoutRequest_preferencesInput,
    Prisma.DimensionIndexUncheckedCreateWithoutRequest_preferencesInput
  >;
  where?: Prisma.DimensionIndexWhereInput;
};

export type DimensionIndexUpdateToOneWithWhereWithoutRequest_preferencesInput =
  {
    where?: Prisma.DimensionIndexWhereInput;
    data: Prisma.XOR<
      Prisma.DimensionIndexUpdateWithoutRequest_preferencesInput,
      Prisma.DimensionIndexUncheckedUpdateWithoutRequest_preferencesInput
    >;
  };

export type DimensionIndexUpdateWithoutRequest_preferencesInput = {
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  category?: Prisma.DimensionCategoryUpdateOneRequiredWithoutIndexesNestedInput;
  experience_dimensions?: Prisma.ExperienceDimensionUpdateManyWithoutDimension_indexNestedInput;
  question_dimensions?: Prisma.QuestionDimensionUpdateManyWithoutDimensionNestedInput;
};

export type DimensionIndexUncheckedUpdateWithoutRequest_preferencesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  category_id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  experience_dimensions?: Prisma.ExperienceDimensionUncheckedUpdateManyWithoutDimension_indexNestedInput;
  question_dimensions?: Prisma.QuestionDimensionUncheckedUpdateManyWithoutDimensionNestedInput;
};

export type DimensionIndexCreateManyCategoryInput = {
  id?: number;
  index_key?: string | null;
  index_name: string;
  data_type: string;
  hard_filter: boolean;
  scale_min?: number | null;
  scale_max?: number | null;
  created_at?: Date | string;
  updated_at?: Date | string;
};

export type DimensionIndexUpdateWithoutCategoryInput = {
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  experience_dimensions?: Prisma.ExperienceDimensionUpdateManyWithoutDimension_indexNestedInput;
  question_dimensions?: Prisma.QuestionDimensionUpdateManyWithoutDimensionNestedInput;
  request_preferences?: Prisma.RequestPreferenceUpdateManyWithoutDimension_indexNestedInput;
};

export type DimensionIndexUncheckedUpdateWithoutCategoryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  experience_dimensions?: Prisma.ExperienceDimensionUncheckedUpdateManyWithoutDimension_indexNestedInput;
  question_dimensions?: Prisma.QuestionDimensionUncheckedUpdateManyWithoutDimensionNestedInput;
  request_preferences?: Prisma.RequestPreferenceUncheckedUpdateManyWithoutDimension_indexNestedInput;
};

export type DimensionIndexUncheckedUpdateManyWithoutCategoryInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number;
  index_key?: Prisma.NullableStringFieldUpdateOperationsInput | string | null;
  index_name?: Prisma.StringFieldUpdateOperationsInput | string;
  data_type?: Prisma.StringFieldUpdateOperationsInput | string;
  hard_filter?: Prisma.BoolFieldUpdateOperationsInput | boolean;
  scale_min?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  scale_max?: Prisma.NullableIntFieldUpdateOperationsInput | number | null;
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string;
};

/**
 * Count Type DimensionIndexCountOutputType
 */

export type DimensionIndexCountOutputType = {
  experience_dimensions: number;
  question_dimensions: number;
  request_preferences: number;
};

export type DimensionIndexCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  experience_dimensions?:
    | boolean
    | DimensionIndexCountOutputTypeCountExperience_dimensionsArgs;
  question_dimensions?:
    | boolean
    | DimensionIndexCountOutputTypeCountQuestion_dimensionsArgs;
  request_preferences?:
    | boolean
    | DimensionIndexCountOutputTypeCountRequest_preferencesArgs;
};

/**
 * DimensionIndexCountOutputType without action
 */
export type DimensionIndexCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndexCountOutputType
   */
  select?: Prisma.DimensionIndexCountOutputTypeSelect<ExtArgs> | null;
};

/**
 * DimensionIndexCountOutputType without action
 */
export type DimensionIndexCountOutputTypeCountExperience_dimensionsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.ExperienceDimensionWhereInput;
};

/**
 * DimensionIndexCountOutputType without action
 */
export type DimensionIndexCountOutputTypeCountQuestion_dimensionsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.QuestionDimensionWhereInput;
};

/**
 * DimensionIndexCountOutputType without action
 */
export type DimensionIndexCountOutputTypeCountRequest_preferencesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.RequestPreferenceWhereInput;
};

export type DimensionIndexSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    index_key?: boolean;
    category_id?: boolean;
    index_name?: boolean;
    data_type?: boolean;
    hard_filter?: boolean;
    scale_min?: boolean;
    scale_max?: boolean;
    created_at?: boolean;
    updated_at?: boolean;
    category?: boolean | Prisma.DimensionCategoryDefaultArgs<ExtArgs>;
    experience_dimensions?:
      | boolean
      | Prisma.DimensionIndex$experience_dimensionsArgs<ExtArgs>;
    question_dimensions?:
      | boolean
      | Prisma.DimensionIndex$question_dimensionsArgs<ExtArgs>;
    request_preferences?:
      | boolean
      | Prisma.DimensionIndex$request_preferencesArgs<ExtArgs>;
    _count?: boolean | Prisma.DimensionIndexCountOutputTypeDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['dimensionIndex']
>;

export type DimensionIndexSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    index_key?: boolean;
    category_id?: boolean;
    index_name?: boolean;
    data_type?: boolean;
    hard_filter?: boolean;
    scale_min?: boolean;
    scale_max?: boolean;
    created_at?: boolean;
    updated_at?: boolean;
    category?: boolean | Prisma.DimensionCategoryDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['dimensionIndex']
>;

export type DimensionIndexSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean;
    index_key?: boolean;
    category_id?: boolean;
    index_name?: boolean;
    data_type?: boolean;
    hard_filter?: boolean;
    scale_min?: boolean;
    scale_max?: boolean;
    created_at?: boolean;
    updated_at?: boolean;
    category?: boolean | Prisma.DimensionCategoryDefaultArgs<ExtArgs>;
  },
  ExtArgs['result']['dimensionIndex']
>;

export type DimensionIndexSelectScalar = {
  id?: boolean;
  index_key?: boolean;
  category_id?: boolean;
  index_name?: boolean;
  data_type?: boolean;
  hard_filter?: boolean;
  scale_min?: boolean;
  scale_max?: boolean;
  created_at?: boolean;
  updated_at?: boolean;
};

export type DimensionIndexOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'index_key'
  | 'category_id'
  | 'index_name'
  | 'data_type'
  | 'hard_filter'
  | 'scale_min'
  | 'scale_max'
  | 'created_at'
  | 'updated_at',
  ExtArgs['result']['dimensionIndex']
>;
export type DimensionIndexInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  category?: boolean | Prisma.DimensionCategoryDefaultArgs<ExtArgs>;
  experience_dimensions?:
    | boolean
    | Prisma.DimensionIndex$experience_dimensionsArgs<ExtArgs>;
  question_dimensions?:
    | boolean
    | Prisma.DimensionIndex$question_dimensionsArgs<ExtArgs>;
  request_preferences?:
    | boolean
    | Prisma.DimensionIndex$request_preferencesArgs<ExtArgs>;
  _count?: boolean | Prisma.DimensionIndexCountOutputTypeDefaultArgs<ExtArgs>;
};
export type DimensionIndexIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  category?: boolean | Prisma.DimensionCategoryDefaultArgs<ExtArgs>;
};
export type DimensionIndexIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  category?: boolean | Prisma.DimensionCategoryDefaultArgs<ExtArgs>;
};

export type $DimensionIndexPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'DimensionIndex';
  objects: {
    category: Prisma.$DimensionCategoryPayload<ExtArgs>;
    experience_dimensions: Prisma.$ExperienceDimensionPayload<ExtArgs>[];
    question_dimensions: Prisma.$QuestionDimensionPayload<ExtArgs>[];
    request_preferences: Prisma.$RequestPreferencePayload<ExtArgs>[];
  };
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: number;
      index_key: string | null;
      category_id: number;
      index_name: string;
      data_type: string;
      hard_filter: boolean;
      scale_min: number | null;
      scale_max: number | null;
      created_at: Date;
      updated_at: Date;
    },
    ExtArgs['result']['dimensionIndex']
  >;
  composites: {};
};

export type DimensionIndexGetPayload<
  S extends boolean | null | undefined | DimensionIndexDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$DimensionIndexPayload, S>;

export type DimensionIndexCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<
  DimensionIndexFindManyArgs,
  'select' | 'include' | 'distinct' | 'omit'
> & {
  select?: DimensionIndexCountAggregateInputType | true;
};

export interface DimensionIndexDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['DimensionIndex'];
    meta: { name: 'DimensionIndex' };
  };
  /**
   * Find zero or one DimensionIndex that matches the filter.
   * @param {DimensionIndexFindUniqueArgs} args - Arguments to find a DimensionIndex
   * @example
   * // Get one DimensionIndex
   * const dimensionIndex = await prisma.dimensionIndex.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DimensionIndexFindUniqueArgs>(
    args: Prisma.SelectSubset<T, DimensionIndexFindUniqueArgs<ExtArgs>>
  ): Prisma.Prisma__DimensionIndexClient<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find one DimensionIndex that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DimensionIndexFindUniqueOrThrowArgs} args - Arguments to find a DimensionIndex
   * @example
   * // Get one DimensionIndex
   * const dimensionIndex = await prisma.dimensionIndex.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DimensionIndexFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, DimensionIndexFindUniqueOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__DimensionIndexClient<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first DimensionIndex that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DimensionIndexFindFirstArgs} args - Arguments to find a DimensionIndex
   * @example
   * // Get one DimensionIndex
   * const dimensionIndex = await prisma.dimensionIndex.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DimensionIndexFindFirstArgs>(
    args?: Prisma.SelectSubset<T, DimensionIndexFindFirstArgs<ExtArgs>>
  ): Prisma.Prisma__DimensionIndexClient<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find the first DimensionIndex that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DimensionIndexFindFirstOrThrowArgs} args - Arguments to find a DimensionIndex
   * @example
   * // Get one DimensionIndex
   * const dimensionIndex = await prisma.dimensionIndex.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DimensionIndexFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, DimensionIndexFindFirstOrThrowArgs<ExtArgs>>
  ): Prisma.Prisma__DimensionIndexClient<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Find zero or more DimensionIndices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DimensionIndexFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DimensionIndices
   * const dimensionIndices = await prisma.dimensionIndex.findMany()
   *
   * // Get first 10 DimensionIndices
   * const dimensionIndices = await prisma.dimensionIndex.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const dimensionIndexWithIdOnly = await prisma.dimensionIndex.findMany({ select: { id: true } })
   *
   */
  findMany<T extends DimensionIndexFindManyArgs>(
    args?: Prisma.SelectSubset<T, DimensionIndexFindManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >;

  /**
   * Create a DimensionIndex.
   * @param {DimensionIndexCreateArgs} args - Arguments to create a DimensionIndex.
   * @example
   * // Create one DimensionIndex
   * const DimensionIndex = await prisma.dimensionIndex.create({
   *   data: {
   *     // ... data to create a DimensionIndex
   *   }
   * })
   *
   */
  create<T extends DimensionIndexCreateArgs>(
    args: Prisma.SelectSubset<T, DimensionIndexCreateArgs<ExtArgs>>
  ): Prisma.Prisma__DimensionIndexClient<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Create many DimensionIndices.
   * @param {DimensionIndexCreateManyArgs} args - Arguments to create many DimensionIndices.
   * @example
   * // Create many DimensionIndices
   * const dimensionIndex = await prisma.dimensionIndex.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends DimensionIndexCreateManyArgs>(
    args?: Prisma.SelectSubset<T, DimensionIndexCreateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Create many DimensionIndices and returns the data saved in the database.
   * @param {DimensionIndexCreateManyAndReturnArgs} args - Arguments to create many DimensionIndices.
   * @example
   * // Create many DimensionIndices
   * const dimensionIndex = await prisma.dimensionIndex.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many DimensionIndices and only return the `id`
   * const dimensionIndexWithIdOnly = await prisma.dimensionIndex.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends DimensionIndexCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      DimensionIndexCreateManyAndReturnArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Delete a DimensionIndex.
   * @param {DimensionIndexDeleteArgs} args - Arguments to delete one DimensionIndex.
   * @example
   * // Delete one DimensionIndex
   * const DimensionIndex = await prisma.dimensionIndex.delete({
   *   where: {
   *     // ... filter to delete one DimensionIndex
   *   }
   * })
   *
   */
  delete<T extends DimensionIndexDeleteArgs>(
    args: Prisma.SelectSubset<T, DimensionIndexDeleteArgs<ExtArgs>>
  ): Prisma.Prisma__DimensionIndexClient<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Update one DimensionIndex.
   * @param {DimensionIndexUpdateArgs} args - Arguments to update one DimensionIndex.
   * @example
   * // Update one DimensionIndex
   * const dimensionIndex = await prisma.dimensionIndex.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends DimensionIndexUpdateArgs>(
    args: Prisma.SelectSubset<T, DimensionIndexUpdateArgs<ExtArgs>>
  ): Prisma.Prisma__DimensionIndexClient<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Delete zero or more DimensionIndices.
   * @param {DimensionIndexDeleteManyArgs} args - Arguments to filter DimensionIndices to delete.
   * @example
   * // Delete a few DimensionIndices
   * const { count } = await prisma.dimensionIndex.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends DimensionIndexDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, DimensionIndexDeleteManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more DimensionIndices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DimensionIndexUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DimensionIndices
   * const dimensionIndex = await prisma.dimensionIndex.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends DimensionIndexUpdateManyArgs>(
    args: Prisma.SelectSubset<T, DimensionIndexUpdateManyArgs<ExtArgs>>
  ): Prisma.PrismaPromise<Prisma.BatchPayload>;

  /**
   * Update zero or more DimensionIndices and returns the data updated in the database.
   * @param {DimensionIndexUpdateManyAndReturnArgs} args - Arguments to update many DimensionIndices.
   * @example
   * // Update many DimensionIndices
   * const dimensionIndex = await prisma.dimensionIndex.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more DimensionIndices and only return the `id`
   * const dimensionIndexWithIdOnly = await prisma.dimensionIndex.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends DimensionIndexUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, DimensionIndexUpdateManyAndReturnArgs<ExtArgs>>
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >;

  /**
   * Create or update one DimensionIndex.
   * @param {DimensionIndexUpsertArgs} args - Arguments to update or create a DimensionIndex.
   * @example
   * // Update or create a DimensionIndex
   * const dimensionIndex = await prisma.dimensionIndex.upsert({
   *   create: {
   *     // ... data to create a DimensionIndex
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DimensionIndex we want to update
   *   }
   * })
   */
  upsert<T extends DimensionIndexUpsertArgs>(
    args: Prisma.SelectSubset<T, DimensionIndexUpsertArgs<ExtArgs>>
  ): Prisma.Prisma__DimensionIndexClient<
    runtime.Types.Result.GetResult<
      Prisma.$DimensionIndexPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >;

  /**
   * Count the number of DimensionIndices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DimensionIndexCountArgs} args - Arguments to filter DimensionIndices to count.
   * @example
   * // Count the number of DimensionIndices
   * const count = await prisma.dimensionIndex.count({
   *   where: {
   *     // ... the filter for the DimensionIndices we want to count
   *   }
   * })
   **/
  count<T extends DimensionIndexCountArgs>(
    args?: Prisma.Subset<T, DimensionIndexCountArgs>
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<
            T['select'],
            DimensionIndexCountAggregateOutputType
          >
      : number
  >;

  /**
   * Allows you to perform aggregations operations on a DimensionIndex.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DimensionIndexAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends DimensionIndexAggregateArgs>(
    args: Prisma.Subset<T, DimensionIndexAggregateArgs>
  ): Prisma.PrismaPromise<GetDimensionIndexAggregateType<T>>;

  /**
   * Group by DimensionIndex.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DimensionIndexGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends DimensionIndexGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DimensionIndexGroupByArgs['orderBy'] }
      : { orderBy?: DimensionIndexGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ];
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`;
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, DimensionIndexGroupByArgs, OrderByArg> &
      InputErrors
  ): {} extends InputErrors
    ? GetDimensionIndexGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>;
  /**
   * Fields of the DimensionIndex model
   */
  readonly fields: DimensionIndexFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DimensionIndex.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DimensionIndexClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise';
  category<T extends Prisma.DimensionCategoryDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.DimensionCategoryDefaultArgs<ExtArgs>>
  ): Prisma.Prisma__DimensionCategoryClient<
    | runtime.Types.Result.GetResult<
        Prisma.$DimensionCategoryPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >;
  experience_dimensions<
    T extends Prisma.DimensionIndex$experience_dimensionsArgs<ExtArgs> = {},
  >(
    args?: Prisma.Subset<
      T,
      Prisma.DimensionIndex$experience_dimensionsArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$ExperienceDimensionPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  question_dimensions<
    T extends Prisma.DimensionIndex$question_dimensionsArgs<ExtArgs> = {},
  >(
    args?: Prisma.Subset<
      T,
      Prisma.DimensionIndex$question_dimensionsArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$QuestionDimensionPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  request_preferences<
    T extends Prisma.DimensionIndex$request_preferencesArgs<ExtArgs> = {},
  >(
    args?: Prisma.Subset<
      T,
      Prisma.DimensionIndex$request_preferencesArgs<ExtArgs>
    >
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$RequestPreferencePayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >;
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>;
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null
  ): runtime.Types.Utils.JsPromise<T | TResult>;
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null
  ): runtime.Types.Utils.JsPromise<T>;
}

/**
 * Fields of the DimensionIndex model
 */
export interface DimensionIndexFieldRefs {
  readonly id: Prisma.FieldRef<'DimensionIndex', 'Int'>;
  readonly index_key: Prisma.FieldRef<'DimensionIndex', 'String'>;
  readonly category_id: Prisma.FieldRef<'DimensionIndex', 'Int'>;
  readonly index_name: Prisma.FieldRef<'DimensionIndex', 'String'>;
  readonly data_type: Prisma.FieldRef<'DimensionIndex', 'String'>;
  readonly hard_filter: Prisma.FieldRef<'DimensionIndex', 'Boolean'>;
  readonly scale_min: Prisma.FieldRef<'DimensionIndex', 'Int'>;
  readonly scale_max: Prisma.FieldRef<'DimensionIndex', 'Int'>;
  readonly created_at: Prisma.FieldRef<'DimensionIndex', 'DateTime'>;
  readonly updated_at: Prisma.FieldRef<'DimensionIndex', 'DateTime'>;
}

// Custom InputTypes
/**
 * DimensionIndex findUnique
 */
export type DimensionIndexFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexInclude<ExtArgs> | null;
  /**
   * Filter, which DimensionIndex to fetch.
   */
  where: Prisma.DimensionIndexWhereUniqueInput;
};

/**
 * DimensionIndex findUniqueOrThrow
 */
export type DimensionIndexFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexInclude<ExtArgs> | null;
  /**
   * Filter, which DimensionIndex to fetch.
   */
  where: Prisma.DimensionIndexWhereUniqueInput;
};

/**
 * DimensionIndex findFirst
 */
export type DimensionIndexFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexInclude<ExtArgs> | null;
  /**
   * Filter, which DimensionIndex to fetch.
   */
  where?: Prisma.DimensionIndexWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of DimensionIndices to fetch.
   */
  orderBy?:
    | Prisma.DimensionIndexOrderByWithRelationInput
    | Prisma.DimensionIndexOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for DimensionIndices.
   */
  cursor?: Prisma.DimensionIndexWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` DimensionIndices from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` DimensionIndices.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of DimensionIndices.
   */
  distinct?:
    | Prisma.DimensionIndexScalarFieldEnum
    | Prisma.DimensionIndexScalarFieldEnum[];
};

/**
 * DimensionIndex findFirstOrThrow
 */
export type DimensionIndexFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexInclude<ExtArgs> | null;
  /**
   * Filter, which DimensionIndex to fetch.
   */
  where?: Prisma.DimensionIndexWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of DimensionIndices to fetch.
   */
  orderBy?:
    | Prisma.DimensionIndexOrderByWithRelationInput
    | Prisma.DimensionIndexOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for DimensionIndices.
   */
  cursor?: Prisma.DimensionIndexWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` DimensionIndices from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` DimensionIndices.
   */
  skip?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of DimensionIndices.
   */
  distinct?:
    | Prisma.DimensionIndexScalarFieldEnum
    | Prisma.DimensionIndexScalarFieldEnum[];
};

/**
 * DimensionIndex findMany
 */
export type DimensionIndexFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexInclude<ExtArgs> | null;
  /**
   * Filter, which DimensionIndices to fetch.
   */
  where?: Prisma.DimensionIndexWhereInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of DimensionIndices to fetch.
   */
  orderBy?:
    | Prisma.DimensionIndexOrderByWithRelationInput
    | Prisma.DimensionIndexOrderByWithRelationInput[];
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing DimensionIndices.
   */
  cursor?: Prisma.DimensionIndexWhereUniqueInput;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` DimensionIndices from the position of the cursor.
   */
  take?: number;
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` DimensionIndices.
   */
  skip?: number;
  distinct?:
    | Prisma.DimensionIndexScalarFieldEnum
    | Prisma.DimensionIndexScalarFieldEnum[];
};

/**
 * DimensionIndex create
 */
export type DimensionIndexCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexInclude<ExtArgs> | null;
  /**
   * The data needed to create a DimensionIndex.
   */
  data: Prisma.XOR<
    Prisma.DimensionIndexCreateInput,
    Prisma.DimensionIndexUncheckedCreateInput
  >;
};

/**
 * DimensionIndex createMany
 */
export type DimensionIndexCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many DimensionIndices.
   */
  data:
    | Prisma.DimensionIndexCreateManyInput
    | Prisma.DimensionIndexCreateManyInput[];
  skipDuplicates?: boolean;
};

/**
 * DimensionIndex createManyAndReturn
 */
export type DimensionIndexCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelectCreateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * The data used to create many DimensionIndices.
   */
  data:
    | Prisma.DimensionIndexCreateManyInput
    | Prisma.DimensionIndexCreateManyInput[];
  skipDuplicates?: boolean;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexIncludeCreateManyAndReturn<ExtArgs> | null;
};

/**
 * DimensionIndex update
 */
export type DimensionIndexUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexInclude<ExtArgs> | null;
  /**
   * The data needed to update a DimensionIndex.
   */
  data: Prisma.XOR<
    Prisma.DimensionIndexUpdateInput,
    Prisma.DimensionIndexUncheckedUpdateInput
  >;
  /**
   * Choose, which DimensionIndex to update.
   */
  where: Prisma.DimensionIndexWhereUniqueInput;
};

/**
 * DimensionIndex updateMany
 */
export type DimensionIndexUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update DimensionIndices.
   */
  data: Prisma.XOR<
    Prisma.DimensionIndexUpdateManyMutationInput,
    Prisma.DimensionIndexUncheckedUpdateManyInput
  >;
  /**
   * Filter which DimensionIndices to update
   */
  where?: Prisma.DimensionIndexWhereInput;
  /**
   * Limit how many DimensionIndices to update.
   */
  limit?: number;
};

/**
 * DimensionIndex updateManyAndReturn
 */
export type DimensionIndexUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelectUpdateManyAndReturn<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * The data used to update DimensionIndices.
   */
  data: Prisma.XOR<
    Prisma.DimensionIndexUpdateManyMutationInput,
    Prisma.DimensionIndexUncheckedUpdateManyInput
  >;
  /**
   * Filter which DimensionIndices to update
   */
  where?: Prisma.DimensionIndexWhereInput;
  /**
   * Limit how many DimensionIndices to update.
   */
  limit?: number;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexIncludeUpdateManyAndReturn<ExtArgs> | null;
};

/**
 * DimensionIndex upsert
 */
export type DimensionIndexUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexInclude<ExtArgs> | null;
  /**
   * The filter to search for the DimensionIndex to update in case it exists.
   */
  where: Prisma.DimensionIndexWhereUniqueInput;
  /**
   * In case the DimensionIndex found by the `where` argument doesn't exist, create a new DimensionIndex with this data.
   */
  create: Prisma.XOR<
    Prisma.DimensionIndexCreateInput,
    Prisma.DimensionIndexUncheckedCreateInput
  >;
  /**
   * In case the DimensionIndex was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.DimensionIndexUpdateInput,
    Prisma.DimensionIndexUncheckedUpdateInput
  >;
};

/**
 * DimensionIndex delete
 */
export type DimensionIndexDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexInclude<ExtArgs> | null;
  /**
   * Filter which DimensionIndex to delete.
   */
  where: Prisma.DimensionIndexWhereUniqueInput;
};

/**
 * DimensionIndex deleteMany
 */
export type DimensionIndexDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which DimensionIndices to delete
   */
  where?: Prisma.DimensionIndexWhereInput;
  /**
   * Limit how many DimensionIndices to delete.
   */
  limit?: number;
};

/**
 * DimensionIndex.experience_dimensions
 */
export type DimensionIndex$experience_dimensionsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the ExperienceDimension
   */
  select?: Prisma.ExperienceDimensionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the ExperienceDimension
   */
  omit?: Prisma.ExperienceDimensionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceDimensionInclude<ExtArgs> | null;
  where?: Prisma.ExperienceDimensionWhereInput;
  orderBy?:
    | Prisma.ExperienceDimensionOrderByWithRelationInput
    | Prisma.ExperienceDimensionOrderByWithRelationInput[];
  cursor?: Prisma.ExperienceDimensionWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.ExperienceDimensionScalarFieldEnum
    | Prisma.ExperienceDimensionScalarFieldEnum[];
};

/**
 * DimensionIndex.question_dimensions
 */
export type DimensionIndex$question_dimensionsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the QuestionDimension
   */
  select?: Prisma.QuestionDimensionSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the QuestionDimension
   */
  omit?: Prisma.QuestionDimensionOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.QuestionDimensionInclude<ExtArgs> | null;
  where?: Prisma.QuestionDimensionWhereInput;
  orderBy?:
    | Prisma.QuestionDimensionOrderByWithRelationInput
    | Prisma.QuestionDimensionOrderByWithRelationInput[];
  cursor?: Prisma.QuestionDimensionWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.QuestionDimensionScalarFieldEnum
    | Prisma.QuestionDimensionScalarFieldEnum[];
};

/**
 * DimensionIndex.request_preferences
 */
export type DimensionIndex$request_preferencesArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the RequestPreference
   */
  select?: Prisma.RequestPreferenceSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the RequestPreference
   */
  omit?: Prisma.RequestPreferenceOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RequestPreferenceInclude<ExtArgs> | null;
  where?: Prisma.RequestPreferenceWhereInput;
  orderBy?:
    | Prisma.RequestPreferenceOrderByWithRelationInput
    | Prisma.RequestPreferenceOrderByWithRelationInput[];
  cursor?: Prisma.RequestPreferenceWhereUniqueInput;
  take?: number;
  skip?: number;
  distinct?:
    | Prisma.RequestPreferenceScalarFieldEnum
    | Prisma.RequestPreferenceScalarFieldEnum[];
};

/**
 * DimensionIndex without action
 */
export type DimensionIndexDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the DimensionIndex
   */
  select?: Prisma.DimensionIndexSelect<ExtArgs> | null;
  /**
   * Omit specific fields from the DimensionIndex
   */
  omit?: Prisma.DimensionIndexOmit<ExtArgs> | null;
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DimensionIndexInclude<ExtArgs> | null;
};
