
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Proposal` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Proposal
 * 
 */
export type ProposalModel = runtime.Types.Result.DefaultSelection<Prisma.$ProposalPayload>

export type AggregateProposal = {
  _count: ProposalCountAggregateOutputType | null
  _avg: ProposalAvgAggregateOutputType | null
  _sum: ProposalSumAggregateOutputType | null
  _min: ProposalMinAggregateOutputType | null
  _max: ProposalMaxAggregateOutputType | null
}

export type ProposalAvgAggregateOutputType = {
  id: number | null
  request_id: number | null
  experience_id: number | null
  base_score: runtime.Decimal | null
  risk_adjustment: runtime.Decimal | null
}

export type ProposalSumAggregateOutputType = {
  id: number | null
  request_id: number | null
  experience_id: number | null
  base_score: runtime.Decimal | null
  risk_adjustment: runtime.Decimal | null
}

export type ProposalMinAggregateOutputType = {
  id: number | null
  request_id: number | null
  experience_id: number | null
  objective_alignment: string | null
  base_score: runtime.Decimal | null
  risk_adjustment: runtime.Decimal | null
  rationale_desc: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type ProposalMaxAggregateOutputType = {
  id: number | null
  request_id: number | null
  experience_id: number | null
  objective_alignment: string | null
  base_score: runtime.Decimal | null
  risk_adjustment: runtime.Decimal | null
  rationale_desc: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type ProposalCountAggregateOutputType = {
  id: number
  request_id: number
  experience_id: number
  objective_alignment: number
  base_score: number
  risk_adjustment: number
  rationale_desc: number
  created_at: number
  updated_at: number
  _all: number
}


export type ProposalAvgAggregateInputType = {
  id?: true
  request_id?: true
  experience_id?: true
  base_score?: true
  risk_adjustment?: true
}

export type ProposalSumAggregateInputType = {
  id?: true
  request_id?: true
  experience_id?: true
  base_score?: true
  risk_adjustment?: true
}

export type ProposalMinAggregateInputType = {
  id?: true
  request_id?: true
  experience_id?: true
  objective_alignment?: true
  base_score?: true
  risk_adjustment?: true
  rationale_desc?: true
  created_at?: true
  updated_at?: true
}

export type ProposalMaxAggregateInputType = {
  id?: true
  request_id?: true
  experience_id?: true
  objective_alignment?: true
  base_score?: true
  risk_adjustment?: true
  rationale_desc?: true
  created_at?: true
  updated_at?: true
}

export type ProposalCountAggregateInputType = {
  id?: true
  request_id?: true
  experience_id?: true
  objective_alignment?: true
  base_score?: true
  risk_adjustment?: true
  rationale_desc?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type ProposalAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proposal to aggregate.
   */
  where?: Prisma.ProposalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proposals to fetch.
   */
  orderBy?: Prisma.ProposalOrderByWithRelationInput | Prisma.ProposalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ProposalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proposals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proposals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Proposals
  **/
  _count?: true | ProposalCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ProposalAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ProposalSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ProposalMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ProposalMaxAggregateInputType
}

export type GetProposalAggregateType<T extends ProposalAggregateArgs> = {
      [P in keyof T & keyof AggregateProposal]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateProposal[P]>
    : Prisma.GetScalarType<T[P], AggregateProposal[P]>
}




export type ProposalGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProposalWhereInput
  orderBy?: Prisma.ProposalOrderByWithAggregationInput | Prisma.ProposalOrderByWithAggregationInput[]
  by: Prisma.ProposalScalarFieldEnum[] | Prisma.ProposalScalarFieldEnum
  having?: Prisma.ProposalScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ProposalCountAggregateInputType | true
  _avg?: ProposalAvgAggregateInputType
  _sum?: ProposalSumAggregateInputType
  _min?: ProposalMinAggregateInputType
  _max?: ProposalMaxAggregateInputType
}

export type ProposalGroupByOutputType = {
  id: number
  request_id: number
  experience_id: number
  objective_alignment: string
  base_score: runtime.Decimal
  risk_adjustment: runtime.Decimal
  rationale_desc: string
  created_at: Date
  updated_at: Date
  _count: ProposalCountAggregateOutputType | null
  _avg: ProposalAvgAggregateOutputType | null
  _sum: ProposalSumAggregateOutputType | null
  _min: ProposalMinAggregateOutputType | null
  _max: ProposalMaxAggregateOutputType | null
}

type GetProposalGroupByPayload<T extends ProposalGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ProposalGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ProposalGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ProposalGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ProposalGroupByOutputType[P]>
      }
    >
  >



export type ProposalWhereInput = {
  AND?: Prisma.ProposalWhereInput | Prisma.ProposalWhereInput[]
  OR?: Prisma.ProposalWhereInput[]
  NOT?: Prisma.ProposalWhereInput | Prisma.ProposalWhereInput[]
  id?: Prisma.IntFilter<"Proposal"> | number
  request_id?: Prisma.IntFilter<"Proposal"> | number
  experience_id?: Prisma.IntFilter<"Proposal"> | number
  objective_alignment?: Prisma.StringFilter<"Proposal"> | string
  base_score?: Prisma.DecimalFilter<"Proposal"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFilter<"Proposal"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFilter<"Proposal"> | string
  created_at?: Prisma.DateTimeFilter<"Proposal"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Proposal"> | Date | string
  experience?: Prisma.XOR<Prisma.ExperienceScalarRelationFilter, Prisma.ExperienceWhereInput>
  request?: Prisma.XOR<Prisma.RequestScalarRelationFilter, Prisma.RequestWhereInput>
}

export type ProposalOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  experience_id?: Prisma.SortOrder
  objective_alignment?: Prisma.SortOrder
  base_score?: Prisma.SortOrder
  risk_adjustment?: Prisma.SortOrder
  rationale_desc?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  experience?: Prisma.ExperienceOrderByWithRelationInput
  request?: Prisma.RequestOrderByWithRelationInput
}

export type ProposalWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ProposalWhereInput | Prisma.ProposalWhereInput[]
  OR?: Prisma.ProposalWhereInput[]
  NOT?: Prisma.ProposalWhereInput | Prisma.ProposalWhereInput[]
  request_id?: Prisma.IntFilter<"Proposal"> | number
  experience_id?: Prisma.IntFilter<"Proposal"> | number
  objective_alignment?: Prisma.StringFilter<"Proposal"> | string
  base_score?: Prisma.DecimalFilter<"Proposal"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFilter<"Proposal"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFilter<"Proposal"> | string
  created_at?: Prisma.DateTimeFilter<"Proposal"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Proposal"> | Date | string
  experience?: Prisma.XOR<Prisma.ExperienceScalarRelationFilter, Prisma.ExperienceWhereInput>
  request?: Prisma.XOR<Prisma.RequestScalarRelationFilter, Prisma.RequestWhereInput>
}, "id">

export type ProposalOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  experience_id?: Prisma.SortOrder
  objective_alignment?: Prisma.SortOrder
  base_score?: Prisma.SortOrder
  risk_adjustment?: Prisma.SortOrder
  rationale_desc?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.ProposalCountOrderByAggregateInput
  _avg?: Prisma.ProposalAvgOrderByAggregateInput
  _max?: Prisma.ProposalMaxOrderByAggregateInput
  _min?: Prisma.ProposalMinOrderByAggregateInput
  _sum?: Prisma.ProposalSumOrderByAggregateInput
}

export type ProposalScalarWhereWithAggregatesInput = {
  AND?: Prisma.ProposalScalarWhereWithAggregatesInput | Prisma.ProposalScalarWhereWithAggregatesInput[]
  OR?: Prisma.ProposalScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ProposalScalarWhereWithAggregatesInput | Prisma.ProposalScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Proposal"> | number
  request_id?: Prisma.IntWithAggregatesFilter<"Proposal"> | number
  experience_id?: Prisma.IntWithAggregatesFilter<"Proposal"> | number
  objective_alignment?: Prisma.StringWithAggregatesFilter<"Proposal"> | string
  base_score?: Prisma.DecimalWithAggregatesFilter<"Proposal"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalWithAggregatesFilter<"Proposal"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringWithAggregatesFilter<"Proposal"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"Proposal"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"Proposal"> | Date | string
}

export type ProposalCreateInput = {
  objective_alignment: string
  base_score: runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment: runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc: string
  created_at?: Date | string
  updated_at?: Date | string
  experience: Prisma.ExperienceCreateNestedOneWithoutProposalsInput
  request: Prisma.RequestCreateNestedOneWithoutProposalsInput
}

export type ProposalUncheckedCreateInput = {
  id?: number
  request_id: number
  experience_id: number
  objective_alignment: string
  base_score: runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment: runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ProposalUpdateInput = {
  objective_alignment?: Prisma.StringFieldUpdateOperationsInput | string
  base_score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experience?: Prisma.ExperienceUpdateOneRequiredWithoutProposalsNestedInput
  request?: Prisma.RequestUpdateOneRequiredWithoutProposalsNestedInput
}

export type ProposalUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  request_id?: Prisma.IntFieldUpdateOperationsInput | number
  experience_id?: Prisma.IntFieldUpdateOperationsInput | number
  objective_alignment?: Prisma.StringFieldUpdateOperationsInput | string
  base_score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProposalCreateManyInput = {
  id?: number
  request_id: number
  experience_id: number
  objective_alignment: string
  base_score: runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment: runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ProposalUpdateManyMutationInput = {
  objective_alignment?: Prisma.StringFieldUpdateOperationsInput | string
  base_score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProposalUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  request_id?: Prisma.IntFieldUpdateOperationsInput | number
  experience_id?: Prisma.IntFieldUpdateOperationsInput | number
  objective_alignment?: Prisma.StringFieldUpdateOperationsInput | string
  base_score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProposalListRelationFilter = {
  every?: Prisma.ProposalWhereInput
  some?: Prisma.ProposalWhereInput
  none?: Prisma.ProposalWhereInput
}

export type ProposalOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ProposalCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  experience_id?: Prisma.SortOrder
  objective_alignment?: Prisma.SortOrder
  base_score?: Prisma.SortOrder
  risk_adjustment?: Prisma.SortOrder
  rationale_desc?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ProposalAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  experience_id?: Prisma.SortOrder
  base_score?: Prisma.SortOrder
  risk_adjustment?: Prisma.SortOrder
}

export type ProposalMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  experience_id?: Prisma.SortOrder
  objective_alignment?: Prisma.SortOrder
  base_score?: Prisma.SortOrder
  risk_adjustment?: Prisma.SortOrder
  rationale_desc?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ProposalMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  experience_id?: Prisma.SortOrder
  objective_alignment?: Prisma.SortOrder
  base_score?: Prisma.SortOrder
  risk_adjustment?: Prisma.SortOrder
  rationale_desc?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type ProposalSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  request_id?: Prisma.SortOrder
  experience_id?: Prisma.SortOrder
  base_score?: Prisma.SortOrder
  risk_adjustment?: Prisma.SortOrder
}

export type ProposalCreateNestedManyWithoutExperienceInput = {
  create?: Prisma.XOR<Prisma.ProposalCreateWithoutExperienceInput, Prisma.ProposalUncheckedCreateWithoutExperienceInput> | Prisma.ProposalCreateWithoutExperienceInput[] | Prisma.ProposalUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.ProposalCreateOrConnectWithoutExperienceInput | Prisma.ProposalCreateOrConnectWithoutExperienceInput[]
  createMany?: Prisma.ProposalCreateManyExperienceInputEnvelope
  connect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
}

export type ProposalUncheckedCreateNestedManyWithoutExperienceInput = {
  create?: Prisma.XOR<Prisma.ProposalCreateWithoutExperienceInput, Prisma.ProposalUncheckedCreateWithoutExperienceInput> | Prisma.ProposalCreateWithoutExperienceInput[] | Prisma.ProposalUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.ProposalCreateOrConnectWithoutExperienceInput | Prisma.ProposalCreateOrConnectWithoutExperienceInput[]
  createMany?: Prisma.ProposalCreateManyExperienceInputEnvelope
  connect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
}

export type ProposalUpdateManyWithoutExperienceNestedInput = {
  create?: Prisma.XOR<Prisma.ProposalCreateWithoutExperienceInput, Prisma.ProposalUncheckedCreateWithoutExperienceInput> | Prisma.ProposalCreateWithoutExperienceInput[] | Prisma.ProposalUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.ProposalCreateOrConnectWithoutExperienceInput | Prisma.ProposalCreateOrConnectWithoutExperienceInput[]
  upsert?: Prisma.ProposalUpsertWithWhereUniqueWithoutExperienceInput | Prisma.ProposalUpsertWithWhereUniqueWithoutExperienceInput[]
  createMany?: Prisma.ProposalCreateManyExperienceInputEnvelope
  set?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  disconnect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  delete?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  connect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  update?: Prisma.ProposalUpdateWithWhereUniqueWithoutExperienceInput | Prisma.ProposalUpdateWithWhereUniqueWithoutExperienceInput[]
  updateMany?: Prisma.ProposalUpdateManyWithWhereWithoutExperienceInput | Prisma.ProposalUpdateManyWithWhereWithoutExperienceInput[]
  deleteMany?: Prisma.ProposalScalarWhereInput | Prisma.ProposalScalarWhereInput[]
}

export type ProposalUncheckedUpdateManyWithoutExperienceNestedInput = {
  create?: Prisma.XOR<Prisma.ProposalCreateWithoutExperienceInput, Prisma.ProposalUncheckedCreateWithoutExperienceInput> | Prisma.ProposalCreateWithoutExperienceInput[] | Prisma.ProposalUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.ProposalCreateOrConnectWithoutExperienceInput | Prisma.ProposalCreateOrConnectWithoutExperienceInput[]
  upsert?: Prisma.ProposalUpsertWithWhereUniqueWithoutExperienceInput | Prisma.ProposalUpsertWithWhereUniqueWithoutExperienceInput[]
  createMany?: Prisma.ProposalCreateManyExperienceInputEnvelope
  set?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  disconnect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  delete?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  connect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  update?: Prisma.ProposalUpdateWithWhereUniqueWithoutExperienceInput | Prisma.ProposalUpdateWithWhereUniqueWithoutExperienceInput[]
  updateMany?: Prisma.ProposalUpdateManyWithWhereWithoutExperienceInput | Prisma.ProposalUpdateManyWithWhereWithoutExperienceInput[]
  deleteMany?: Prisma.ProposalScalarWhereInput | Prisma.ProposalScalarWhereInput[]
}

export type ProposalCreateNestedManyWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.ProposalCreateWithoutRequestInput, Prisma.ProposalUncheckedCreateWithoutRequestInput> | Prisma.ProposalCreateWithoutRequestInput[] | Prisma.ProposalUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.ProposalCreateOrConnectWithoutRequestInput | Prisma.ProposalCreateOrConnectWithoutRequestInput[]
  createMany?: Prisma.ProposalCreateManyRequestInputEnvelope
  connect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
}

export type ProposalUncheckedCreateNestedManyWithoutRequestInput = {
  create?: Prisma.XOR<Prisma.ProposalCreateWithoutRequestInput, Prisma.ProposalUncheckedCreateWithoutRequestInput> | Prisma.ProposalCreateWithoutRequestInput[] | Prisma.ProposalUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.ProposalCreateOrConnectWithoutRequestInput | Prisma.ProposalCreateOrConnectWithoutRequestInput[]
  createMany?: Prisma.ProposalCreateManyRequestInputEnvelope
  connect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
}

export type ProposalUpdateManyWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.ProposalCreateWithoutRequestInput, Prisma.ProposalUncheckedCreateWithoutRequestInput> | Prisma.ProposalCreateWithoutRequestInput[] | Prisma.ProposalUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.ProposalCreateOrConnectWithoutRequestInput | Prisma.ProposalCreateOrConnectWithoutRequestInput[]
  upsert?: Prisma.ProposalUpsertWithWhereUniqueWithoutRequestInput | Prisma.ProposalUpsertWithWhereUniqueWithoutRequestInput[]
  createMany?: Prisma.ProposalCreateManyRequestInputEnvelope
  set?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  disconnect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  delete?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  connect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  update?: Prisma.ProposalUpdateWithWhereUniqueWithoutRequestInput | Prisma.ProposalUpdateWithWhereUniqueWithoutRequestInput[]
  updateMany?: Prisma.ProposalUpdateManyWithWhereWithoutRequestInput | Prisma.ProposalUpdateManyWithWhereWithoutRequestInput[]
  deleteMany?: Prisma.ProposalScalarWhereInput | Prisma.ProposalScalarWhereInput[]
}

export type ProposalUncheckedUpdateManyWithoutRequestNestedInput = {
  create?: Prisma.XOR<Prisma.ProposalCreateWithoutRequestInput, Prisma.ProposalUncheckedCreateWithoutRequestInput> | Prisma.ProposalCreateWithoutRequestInput[] | Prisma.ProposalUncheckedCreateWithoutRequestInput[]
  connectOrCreate?: Prisma.ProposalCreateOrConnectWithoutRequestInput | Prisma.ProposalCreateOrConnectWithoutRequestInput[]
  upsert?: Prisma.ProposalUpsertWithWhereUniqueWithoutRequestInput | Prisma.ProposalUpsertWithWhereUniqueWithoutRequestInput[]
  createMany?: Prisma.ProposalCreateManyRequestInputEnvelope
  set?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  disconnect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  delete?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  connect?: Prisma.ProposalWhereUniqueInput | Prisma.ProposalWhereUniqueInput[]
  update?: Prisma.ProposalUpdateWithWhereUniqueWithoutRequestInput | Prisma.ProposalUpdateWithWhereUniqueWithoutRequestInput[]
  updateMany?: Prisma.ProposalUpdateManyWithWhereWithoutRequestInput | Prisma.ProposalUpdateManyWithWhereWithoutRequestInput[]
  deleteMany?: Prisma.ProposalScalarWhereInput | Prisma.ProposalScalarWhereInput[]
}

export type ProposalCreateWithoutExperienceInput = {
  objective_alignment: string
  base_score: runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment: runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc: string
  created_at?: Date | string
  updated_at?: Date | string
  request: Prisma.RequestCreateNestedOneWithoutProposalsInput
}

export type ProposalUncheckedCreateWithoutExperienceInput = {
  id?: number
  request_id: number
  objective_alignment: string
  base_score: runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment: runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ProposalCreateOrConnectWithoutExperienceInput = {
  where: Prisma.ProposalWhereUniqueInput
  create: Prisma.XOR<Prisma.ProposalCreateWithoutExperienceInput, Prisma.ProposalUncheckedCreateWithoutExperienceInput>
}

export type ProposalCreateManyExperienceInputEnvelope = {
  data: Prisma.ProposalCreateManyExperienceInput | Prisma.ProposalCreateManyExperienceInput[]
  skipDuplicates?: boolean
}

export type ProposalUpsertWithWhereUniqueWithoutExperienceInput = {
  where: Prisma.ProposalWhereUniqueInput
  update: Prisma.XOR<Prisma.ProposalUpdateWithoutExperienceInput, Prisma.ProposalUncheckedUpdateWithoutExperienceInput>
  create: Prisma.XOR<Prisma.ProposalCreateWithoutExperienceInput, Prisma.ProposalUncheckedCreateWithoutExperienceInput>
}

export type ProposalUpdateWithWhereUniqueWithoutExperienceInput = {
  where: Prisma.ProposalWhereUniqueInput
  data: Prisma.XOR<Prisma.ProposalUpdateWithoutExperienceInput, Prisma.ProposalUncheckedUpdateWithoutExperienceInput>
}

export type ProposalUpdateManyWithWhereWithoutExperienceInput = {
  where: Prisma.ProposalScalarWhereInput
  data: Prisma.XOR<Prisma.ProposalUpdateManyMutationInput, Prisma.ProposalUncheckedUpdateManyWithoutExperienceInput>
}

export type ProposalScalarWhereInput = {
  AND?: Prisma.ProposalScalarWhereInput | Prisma.ProposalScalarWhereInput[]
  OR?: Prisma.ProposalScalarWhereInput[]
  NOT?: Prisma.ProposalScalarWhereInput | Prisma.ProposalScalarWhereInput[]
  id?: Prisma.IntFilter<"Proposal"> | number
  request_id?: Prisma.IntFilter<"Proposal"> | number
  experience_id?: Prisma.IntFilter<"Proposal"> | number
  objective_alignment?: Prisma.StringFilter<"Proposal"> | string
  base_score?: Prisma.DecimalFilter<"Proposal"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFilter<"Proposal"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFilter<"Proposal"> | string
  created_at?: Prisma.DateTimeFilter<"Proposal"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"Proposal"> | Date | string
}

export type ProposalCreateWithoutRequestInput = {
  objective_alignment: string
  base_score: runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment: runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc: string
  created_at?: Date | string
  updated_at?: Date | string
  experience: Prisma.ExperienceCreateNestedOneWithoutProposalsInput
}

export type ProposalUncheckedCreateWithoutRequestInput = {
  id?: number
  experience_id: number
  objective_alignment: string
  base_score: runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment: runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ProposalCreateOrConnectWithoutRequestInput = {
  where: Prisma.ProposalWhereUniqueInput
  create: Prisma.XOR<Prisma.ProposalCreateWithoutRequestInput, Prisma.ProposalUncheckedCreateWithoutRequestInput>
}

export type ProposalCreateManyRequestInputEnvelope = {
  data: Prisma.ProposalCreateManyRequestInput | Prisma.ProposalCreateManyRequestInput[]
  skipDuplicates?: boolean
}

export type ProposalUpsertWithWhereUniqueWithoutRequestInput = {
  where: Prisma.ProposalWhereUniqueInput
  update: Prisma.XOR<Prisma.ProposalUpdateWithoutRequestInput, Prisma.ProposalUncheckedUpdateWithoutRequestInput>
  create: Prisma.XOR<Prisma.ProposalCreateWithoutRequestInput, Prisma.ProposalUncheckedCreateWithoutRequestInput>
}

export type ProposalUpdateWithWhereUniqueWithoutRequestInput = {
  where: Prisma.ProposalWhereUniqueInput
  data: Prisma.XOR<Prisma.ProposalUpdateWithoutRequestInput, Prisma.ProposalUncheckedUpdateWithoutRequestInput>
}

export type ProposalUpdateManyWithWhereWithoutRequestInput = {
  where: Prisma.ProposalScalarWhereInput
  data: Prisma.XOR<Prisma.ProposalUpdateManyMutationInput, Prisma.ProposalUncheckedUpdateManyWithoutRequestInput>
}

export type ProposalCreateManyExperienceInput = {
  id?: number
  request_id: number
  objective_alignment: string
  base_score: runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment: runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ProposalUpdateWithoutExperienceInput = {
  objective_alignment?: Prisma.StringFieldUpdateOperationsInput | string
  base_score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  request?: Prisma.RequestUpdateOneRequiredWithoutProposalsNestedInput
}

export type ProposalUncheckedUpdateWithoutExperienceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  request_id?: Prisma.IntFieldUpdateOperationsInput | number
  objective_alignment?: Prisma.StringFieldUpdateOperationsInput | string
  base_score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProposalUncheckedUpdateManyWithoutExperienceInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  request_id?: Prisma.IntFieldUpdateOperationsInput | number
  objective_alignment?: Prisma.StringFieldUpdateOperationsInput | string
  base_score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProposalCreateManyRequestInput = {
  id?: number
  experience_id: number
  objective_alignment: string
  base_score: runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment: runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type ProposalUpdateWithoutRequestInput = {
  objective_alignment?: Prisma.StringFieldUpdateOperationsInput | string
  base_score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  experience?: Prisma.ExperienceUpdateOneRequiredWithoutProposalsNestedInput
}

export type ProposalUncheckedUpdateWithoutRequestInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  experience_id?: Prisma.IntFieldUpdateOperationsInput | number
  objective_alignment?: Prisma.StringFieldUpdateOperationsInput | string
  base_score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ProposalUncheckedUpdateManyWithoutRequestInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  experience_id?: Prisma.IntFieldUpdateOperationsInput | number
  objective_alignment?: Prisma.StringFieldUpdateOperationsInput | string
  base_score?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  risk_adjustment?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  rationale_desc?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ProposalSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  request_id?: boolean
  experience_id?: boolean
  objective_alignment?: boolean
  base_score?: boolean
  risk_adjustment?: boolean
  rationale_desc?: boolean
  created_at?: boolean
  updated_at?: boolean
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proposal"]>

export type ProposalSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  request_id?: boolean
  experience_id?: boolean
  objective_alignment?: boolean
  base_score?: boolean
  risk_adjustment?: boolean
  rationale_desc?: boolean
  created_at?: boolean
  updated_at?: boolean
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proposal"]>

export type ProposalSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  request_id?: boolean
  experience_id?: boolean
  objective_alignment?: boolean
  base_score?: boolean
  risk_adjustment?: boolean
  rationale_desc?: boolean
  created_at?: boolean
  updated_at?: boolean
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["proposal"]>

export type ProposalSelectScalar = {
  id?: boolean
  request_id?: boolean
  experience_id?: boolean
  objective_alignment?: boolean
  base_score?: boolean
  risk_adjustment?: boolean
  rationale_desc?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type ProposalOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "request_id" | "experience_id" | "objective_alignment" | "base_score" | "risk_adjustment" | "rationale_desc" | "created_at" | "updated_at", ExtArgs["result"]["proposal"]>
export type ProposalInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}
export type ProposalIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}
export type ProposalIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  request?: boolean | Prisma.RequestDefaultArgs<ExtArgs>
}

export type $ProposalPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Proposal"
  objects: {
    experience: Prisma.$ExperiencePayload<ExtArgs>
    request: Prisma.$RequestPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    request_id: number
    experience_id: number
    objective_alignment: string
    base_score: runtime.Decimal
    risk_adjustment: runtime.Decimal
    rationale_desc: string
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["proposal"]>
  composites: {}
}

export type ProposalGetPayload<S extends boolean | null | undefined | ProposalDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ProposalPayload, S>

export type ProposalCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ProposalFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ProposalCountAggregateInputType | true
  }

export interface ProposalDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Proposal'], meta: { name: 'Proposal' } }
  /**
   * Find zero or one Proposal that matches the filter.
   * @param {ProposalFindUniqueArgs} args - Arguments to find a Proposal
   * @example
   * // Get one Proposal
   * const proposal = await prisma.proposal.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ProposalFindUniqueArgs>(args: Prisma.SelectSubset<T, ProposalFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ProposalClient<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Proposal that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ProposalFindUniqueOrThrowArgs} args - Arguments to find a Proposal
   * @example
   * // Get one Proposal
   * const proposal = await prisma.proposal.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ProposalFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ProposalFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProposalClient<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proposal that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposalFindFirstArgs} args - Arguments to find a Proposal
   * @example
   * // Get one Proposal
   * const proposal = await prisma.proposal.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ProposalFindFirstArgs>(args?: Prisma.SelectSubset<T, ProposalFindFirstArgs<ExtArgs>>): Prisma.Prisma__ProposalClient<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Proposal that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposalFindFirstOrThrowArgs} args - Arguments to find a Proposal
   * @example
   * // Get one Proposal
   * const proposal = await prisma.proposal.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ProposalFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ProposalFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ProposalClient<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Proposals that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposalFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Proposals
   * const proposals = await prisma.proposal.findMany()
   * 
   * // Get first 10 Proposals
   * const proposals = await prisma.proposal.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const proposalWithIdOnly = await prisma.proposal.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ProposalFindManyArgs>(args?: Prisma.SelectSubset<T, ProposalFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Proposal.
   * @param {ProposalCreateArgs} args - Arguments to create a Proposal.
   * @example
   * // Create one Proposal
   * const Proposal = await prisma.proposal.create({
   *   data: {
   *     // ... data to create a Proposal
   *   }
   * })
   * 
   */
  create<T extends ProposalCreateArgs>(args: Prisma.SelectSubset<T, ProposalCreateArgs<ExtArgs>>): Prisma.Prisma__ProposalClient<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Proposals.
   * @param {ProposalCreateManyArgs} args - Arguments to create many Proposals.
   * @example
   * // Create many Proposals
   * const proposal = await prisma.proposal.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ProposalCreateManyArgs>(args?: Prisma.SelectSubset<T, ProposalCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Proposals and returns the data saved in the database.
   * @param {ProposalCreateManyAndReturnArgs} args - Arguments to create many Proposals.
   * @example
   * // Create many Proposals
   * const proposal = await prisma.proposal.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Proposals and only return the `id`
   * const proposalWithIdOnly = await prisma.proposal.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ProposalCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ProposalCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Proposal.
   * @param {ProposalDeleteArgs} args - Arguments to delete one Proposal.
   * @example
   * // Delete one Proposal
   * const Proposal = await prisma.proposal.delete({
   *   where: {
   *     // ... filter to delete one Proposal
   *   }
   * })
   * 
   */
  delete<T extends ProposalDeleteArgs>(args: Prisma.SelectSubset<T, ProposalDeleteArgs<ExtArgs>>): Prisma.Prisma__ProposalClient<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Proposal.
   * @param {ProposalUpdateArgs} args - Arguments to update one Proposal.
   * @example
   * // Update one Proposal
   * const proposal = await prisma.proposal.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ProposalUpdateArgs>(args: Prisma.SelectSubset<T, ProposalUpdateArgs<ExtArgs>>): Prisma.Prisma__ProposalClient<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Proposals.
   * @param {ProposalDeleteManyArgs} args - Arguments to filter Proposals to delete.
   * @example
   * // Delete a few Proposals
   * const { count } = await prisma.proposal.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ProposalDeleteManyArgs>(args?: Prisma.SelectSubset<T, ProposalDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proposals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposalUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Proposals
   * const proposal = await prisma.proposal.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ProposalUpdateManyArgs>(args: Prisma.SelectSubset<T, ProposalUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Proposals and returns the data updated in the database.
   * @param {ProposalUpdateManyAndReturnArgs} args - Arguments to update many Proposals.
   * @example
   * // Update many Proposals
   * const proposal = await prisma.proposal.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Proposals and only return the `id`
   * const proposalWithIdOnly = await prisma.proposal.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ProposalUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ProposalUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Proposal.
   * @param {ProposalUpsertArgs} args - Arguments to update or create a Proposal.
   * @example
   * // Update or create a Proposal
   * const proposal = await prisma.proposal.upsert({
   *   create: {
   *     // ... data to create a Proposal
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Proposal we want to update
   *   }
   * })
   */
  upsert<T extends ProposalUpsertArgs>(args: Prisma.SelectSubset<T, ProposalUpsertArgs<ExtArgs>>): Prisma.Prisma__ProposalClient<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Proposals.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposalCountArgs} args - Arguments to filter Proposals to count.
   * @example
   * // Count the number of Proposals
   * const count = await prisma.proposal.count({
   *   where: {
   *     // ... the filter for the Proposals we want to count
   *   }
   * })
  **/
  count<T extends ProposalCountArgs>(
    args?: Prisma.Subset<T, ProposalCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ProposalCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Proposal.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposalAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ProposalAggregateArgs>(args: Prisma.Subset<T, ProposalAggregateArgs>): Prisma.PrismaPromise<GetProposalAggregateType<T>>

  /**
   * Group by Proposal.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ProposalGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ProposalGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ProposalGroupByArgs['orderBy'] }
      : { orderBy?: ProposalGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ProposalGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetProposalGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Proposal model
 */
readonly fields: ProposalFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Proposal.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ProposalClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  experience<T extends Prisma.ExperienceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ExperienceDefaultArgs<ExtArgs>>): Prisma.Prisma__ExperienceClient<runtime.Types.Result.GetResult<Prisma.$ExperiencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  request<T extends Prisma.RequestDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RequestDefaultArgs<ExtArgs>>): Prisma.Prisma__RequestClient<runtime.Types.Result.GetResult<Prisma.$RequestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Proposal model
 */
export interface ProposalFieldRefs {
  readonly id: Prisma.FieldRef<"Proposal", 'Int'>
  readonly request_id: Prisma.FieldRef<"Proposal", 'Int'>
  readonly experience_id: Prisma.FieldRef<"Proposal", 'Int'>
  readonly objective_alignment: Prisma.FieldRef<"Proposal", 'String'>
  readonly base_score: Prisma.FieldRef<"Proposal", 'Decimal'>
  readonly risk_adjustment: Prisma.FieldRef<"Proposal", 'Decimal'>
  readonly rationale_desc: Prisma.FieldRef<"Proposal", 'String'>
  readonly created_at: Prisma.FieldRef<"Proposal", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"Proposal", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Proposal findUnique
 */
export type ProposalFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
  /**
   * Filter, which Proposal to fetch.
   */
  where: Prisma.ProposalWhereUniqueInput
}

/**
 * Proposal findUniqueOrThrow
 */
export type ProposalFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
  /**
   * Filter, which Proposal to fetch.
   */
  where: Prisma.ProposalWhereUniqueInput
}

/**
 * Proposal findFirst
 */
export type ProposalFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
  /**
   * Filter, which Proposal to fetch.
   */
  where?: Prisma.ProposalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proposals to fetch.
   */
  orderBy?: Prisma.ProposalOrderByWithRelationInput | Prisma.ProposalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proposals.
   */
  cursor?: Prisma.ProposalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proposals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proposals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proposals.
   */
  distinct?: Prisma.ProposalScalarFieldEnum | Prisma.ProposalScalarFieldEnum[]
}

/**
 * Proposal findFirstOrThrow
 */
export type ProposalFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
  /**
   * Filter, which Proposal to fetch.
   */
  where?: Prisma.ProposalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proposals to fetch.
   */
  orderBy?: Prisma.ProposalOrderByWithRelationInput | Prisma.ProposalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Proposals.
   */
  cursor?: Prisma.ProposalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proposals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proposals.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Proposals.
   */
  distinct?: Prisma.ProposalScalarFieldEnum | Prisma.ProposalScalarFieldEnum[]
}

/**
 * Proposal findMany
 */
export type ProposalFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
  /**
   * Filter, which Proposals to fetch.
   */
  where?: Prisma.ProposalWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Proposals to fetch.
   */
  orderBy?: Prisma.ProposalOrderByWithRelationInput | Prisma.ProposalOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Proposals.
   */
  cursor?: Prisma.ProposalWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Proposals from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Proposals.
   */
  skip?: number
  distinct?: Prisma.ProposalScalarFieldEnum | Prisma.ProposalScalarFieldEnum[]
}

/**
 * Proposal create
 */
export type ProposalCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
  /**
   * The data needed to create a Proposal.
   */
  data: Prisma.XOR<Prisma.ProposalCreateInput, Prisma.ProposalUncheckedCreateInput>
}

/**
 * Proposal createMany
 */
export type ProposalCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Proposals.
   */
  data: Prisma.ProposalCreateManyInput | Prisma.ProposalCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Proposal createManyAndReturn
 */
export type ProposalCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * The data used to create many Proposals.
   */
  data: Prisma.ProposalCreateManyInput | Prisma.ProposalCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Proposal update
 */
export type ProposalUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
  /**
   * The data needed to update a Proposal.
   */
  data: Prisma.XOR<Prisma.ProposalUpdateInput, Prisma.ProposalUncheckedUpdateInput>
  /**
   * Choose, which Proposal to update.
   */
  where: Prisma.ProposalWhereUniqueInput
}

/**
 * Proposal updateMany
 */
export type ProposalUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Proposals.
   */
  data: Prisma.XOR<Prisma.ProposalUpdateManyMutationInput, Prisma.ProposalUncheckedUpdateManyInput>
  /**
   * Filter which Proposals to update
   */
  where?: Prisma.ProposalWhereInput
  /**
   * Limit how many Proposals to update.
   */
  limit?: number
}

/**
 * Proposal updateManyAndReturn
 */
export type ProposalUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * The data used to update Proposals.
   */
  data: Prisma.XOR<Prisma.ProposalUpdateManyMutationInput, Prisma.ProposalUncheckedUpdateManyInput>
  /**
   * Filter which Proposals to update
   */
  where?: Prisma.ProposalWhereInput
  /**
   * Limit how many Proposals to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Proposal upsert
 */
export type ProposalUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
  /**
   * The filter to search for the Proposal to update in case it exists.
   */
  where: Prisma.ProposalWhereUniqueInput
  /**
   * In case the Proposal found by the `where` argument doesn't exist, create a new Proposal with this data.
   */
  create: Prisma.XOR<Prisma.ProposalCreateInput, Prisma.ProposalUncheckedCreateInput>
  /**
   * In case the Proposal was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ProposalUpdateInput, Prisma.ProposalUncheckedUpdateInput>
}

/**
 * Proposal delete
 */
export type ProposalDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
  /**
   * Filter which Proposal to delete.
   */
  where: Prisma.ProposalWhereUniqueInput
}

/**
 * Proposal deleteMany
 */
export type ProposalDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Proposals to delete
   */
  where?: Prisma.ProposalWhereInput
  /**
   * Limit how many Proposals to delete.
   */
  limit?: number
}

/**
 * Proposal without action
 */
export type ProposalDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
}
