
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TeamVector` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TeamVector
 * 
 */
export type TeamVectorModel = runtime.Types.Result.DefaultSelection<Prisma.$TeamVectorPayload>

export type AggregateTeamVector = {
  _count: TeamVectorCountAggregateOutputType | null
  _avg: TeamVectorAvgAggregateOutputType | null
  _sum: TeamVectorSumAggregateOutputType | null
  _min: TeamVectorMinAggregateOutputType | null
  _max: TeamVectorMaxAggregateOutputType | null
}

export type TeamVectorAvgAggregateOutputType = {
  id: number | null
  team_id: number | null
}

export type TeamVectorSumAggregateOutputType = {
  id: number | null
  team_id: number | null
}

export type TeamVectorMinAggregateOutputType = {
  id: number | null
  team_id: number | null
  vector_json: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type TeamVectorMaxAggregateOutputType = {
  id: number | null
  team_id: number | null
  vector_json: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type TeamVectorCountAggregateOutputType = {
  id: number
  team_id: number
  vector_json: number
  created_at: number
  updated_at: number
  _all: number
}


export type TeamVectorAvgAggregateInputType = {
  id?: true
  team_id?: true
}

export type TeamVectorSumAggregateInputType = {
  id?: true
  team_id?: true
}

export type TeamVectorMinAggregateInputType = {
  id?: true
  team_id?: true
  vector_json?: true
  created_at?: true
  updated_at?: true
}

export type TeamVectorMaxAggregateInputType = {
  id?: true
  team_id?: true
  vector_json?: true
  created_at?: true
  updated_at?: true
}

export type TeamVectorCountAggregateInputType = {
  id?: true
  team_id?: true
  vector_json?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type TeamVectorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TeamVector to aggregate.
   */
  where?: Prisma.TeamVectorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamVectors to fetch.
   */
  orderBy?: Prisma.TeamVectorOrderByWithRelationInput | Prisma.TeamVectorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TeamVectorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamVectors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamVectors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TeamVectors
  **/
  _count?: true | TeamVectorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TeamVectorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TeamVectorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TeamVectorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TeamVectorMaxAggregateInputType
}

export type GetTeamVectorAggregateType<T extends TeamVectorAggregateArgs> = {
      [P in keyof T & keyof AggregateTeamVector]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTeamVector[P]>
    : Prisma.GetScalarType<T[P], AggregateTeamVector[P]>
}




export type TeamVectorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TeamVectorWhereInput
  orderBy?: Prisma.TeamVectorOrderByWithAggregationInput | Prisma.TeamVectorOrderByWithAggregationInput[]
  by: Prisma.TeamVectorScalarFieldEnum[] | Prisma.TeamVectorScalarFieldEnum
  having?: Prisma.TeamVectorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TeamVectorCountAggregateInputType | true
  _avg?: TeamVectorAvgAggregateInputType
  _sum?: TeamVectorSumAggregateInputType
  _min?: TeamVectorMinAggregateInputType
  _max?: TeamVectorMaxAggregateInputType
}

export type TeamVectorGroupByOutputType = {
  id: number
  team_id: number
  vector_json: string
  created_at: Date
  updated_at: Date
  _count: TeamVectorCountAggregateOutputType | null
  _avg: TeamVectorAvgAggregateOutputType | null
  _sum: TeamVectorSumAggregateOutputType | null
  _min: TeamVectorMinAggregateOutputType | null
  _max: TeamVectorMaxAggregateOutputType | null
}

type GetTeamVectorGroupByPayload<T extends TeamVectorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TeamVectorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TeamVectorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TeamVectorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TeamVectorGroupByOutputType[P]>
      }
    >
  >



export type TeamVectorWhereInput = {
  AND?: Prisma.TeamVectorWhereInput | Prisma.TeamVectorWhereInput[]
  OR?: Prisma.TeamVectorWhereInput[]
  NOT?: Prisma.TeamVectorWhereInput | Prisma.TeamVectorWhereInput[]
  id?: Prisma.IntFilter<"TeamVector"> | number
  team_id?: Prisma.IntFilter<"TeamVector"> | number
  vector_json?: Prisma.StringFilter<"TeamVector"> | string
  created_at?: Prisma.DateTimeFilter<"TeamVector"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"TeamVector"> | Date | string
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
}

export type TeamVectorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  team_id?: Prisma.SortOrder
  vector_json?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  team?: Prisma.TeamOrderByWithRelationInput
}

export type TeamVectorWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  team_id?: number
  AND?: Prisma.TeamVectorWhereInput | Prisma.TeamVectorWhereInput[]
  OR?: Prisma.TeamVectorWhereInput[]
  NOT?: Prisma.TeamVectorWhereInput | Prisma.TeamVectorWhereInput[]
  vector_json?: Prisma.StringFilter<"TeamVector"> | string
  created_at?: Prisma.DateTimeFilter<"TeamVector"> | Date | string
  updated_at?: Prisma.DateTimeFilter<"TeamVector"> | Date | string
  team?: Prisma.XOR<Prisma.TeamScalarRelationFilter, Prisma.TeamWhereInput>
}, "id" | "team_id">

export type TeamVectorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  team_id?: Prisma.SortOrder
  vector_json?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.TeamVectorCountOrderByAggregateInput
  _avg?: Prisma.TeamVectorAvgOrderByAggregateInput
  _max?: Prisma.TeamVectorMaxOrderByAggregateInput
  _min?: Prisma.TeamVectorMinOrderByAggregateInput
  _sum?: Prisma.TeamVectorSumOrderByAggregateInput
}

export type TeamVectorScalarWhereWithAggregatesInput = {
  AND?: Prisma.TeamVectorScalarWhereWithAggregatesInput | Prisma.TeamVectorScalarWhereWithAggregatesInput[]
  OR?: Prisma.TeamVectorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TeamVectorScalarWhereWithAggregatesInput | Prisma.TeamVectorScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"TeamVector"> | number
  team_id?: Prisma.IntWithAggregatesFilter<"TeamVector"> | number
  vector_json?: Prisma.StringWithAggregatesFilter<"TeamVector"> | string
  created_at?: Prisma.DateTimeWithAggregatesFilter<"TeamVector"> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<"TeamVector"> | Date | string
}

export type TeamVectorCreateInput = {
  vector_json: string
  created_at?: Date | string
  updated_at?: Date | string
  team: Prisma.TeamCreateNestedOneWithoutTeam_vectorInput
}

export type TeamVectorUncheckedCreateInput = {
  id?: number
  team_id: number
  vector_json: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type TeamVectorUpdateInput = {
  vector_json?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  team?: Prisma.TeamUpdateOneRequiredWithoutTeam_vectorNestedInput
}

export type TeamVectorUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  team_id?: Prisma.IntFieldUpdateOperationsInput | number
  vector_json?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TeamVectorCreateManyInput = {
  id?: number
  team_id: number
  vector_json: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type TeamVectorUpdateManyMutationInput = {
  vector_json?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TeamVectorUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  team_id?: Prisma.IntFieldUpdateOperationsInput | number
  vector_json?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TeamVectorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  team_id?: Prisma.SortOrder
  vector_json?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type TeamVectorAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  team_id?: Prisma.SortOrder
}

export type TeamVectorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  team_id?: Prisma.SortOrder
  vector_json?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type TeamVectorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  team_id?: Prisma.SortOrder
  vector_json?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type TeamVectorSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  team_id?: Prisma.SortOrder
}

export type TeamVectorNullableScalarRelationFilter = {
  is?: Prisma.TeamVectorWhereInput | null
  isNot?: Prisma.TeamVectorWhereInput | null
}

export type TeamVectorCreateNestedOneWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TeamVectorCreateWithoutTeamInput, Prisma.TeamVectorUncheckedCreateWithoutTeamInput>
  connectOrCreate?: Prisma.TeamVectorCreateOrConnectWithoutTeamInput
  connect?: Prisma.TeamVectorWhereUniqueInput
}

export type TeamVectorUncheckedCreateNestedOneWithoutTeamInput = {
  create?: Prisma.XOR<Prisma.TeamVectorCreateWithoutTeamInput, Prisma.TeamVectorUncheckedCreateWithoutTeamInput>
  connectOrCreate?: Prisma.TeamVectorCreateOrConnectWithoutTeamInput
  connect?: Prisma.TeamVectorWhereUniqueInput
}

export type TeamVectorUpdateOneWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TeamVectorCreateWithoutTeamInput, Prisma.TeamVectorUncheckedCreateWithoutTeamInput>
  connectOrCreate?: Prisma.TeamVectorCreateOrConnectWithoutTeamInput
  upsert?: Prisma.TeamVectorUpsertWithoutTeamInput
  disconnect?: Prisma.TeamVectorWhereInput | boolean
  delete?: Prisma.TeamVectorWhereInput | boolean
  connect?: Prisma.TeamVectorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TeamVectorUpdateToOneWithWhereWithoutTeamInput, Prisma.TeamVectorUpdateWithoutTeamInput>, Prisma.TeamVectorUncheckedUpdateWithoutTeamInput>
}

export type TeamVectorUncheckedUpdateOneWithoutTeamNestedInput = {
  create?: Prisma.XOR<Prisma.TeamVectorCreateWithoutTeamInput, Prisma.TeamVectorUncheckedCreateWithoutTeamInput>
  connectOrCreate?: Prisma.TeamVectorCreateOrConnectWithoutTeamInput
  upsert?: Prisma.TeamVectorUpsertWithoutTeamInput
  disconnect?: Prisma.TeamVectorWhereInput | boolean
  delete?: Prisma.TeamVectorWhereInput | boolean
  connect?: Prisma.TeamVectorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TeamVectorUpdateToOneWithWhereWithoutTeamInput, Prisma.TeamVectorUpdateWithoutTeamInput>, Prisma.TeamVectorUncheckedUpdateWithoutTeamInput>
}

export type TeamVectorCreateWithoutTeamInput = {
  vector_json: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type TeamVectorUncheckedCreateWithoutTeamInput = {
  id?: number
  vector_json: string
  created_at?: Date | string
  updated_at?: Date | string
}

export type TeamVectorCreateOrConnectWithoutTeamInput = {
  where: Prisma.TeamVectorWhereUniqueInput
  create: Prisma.XOR<Prisma.TeamVectorCreateWithoutTeamInput, Prisma.TeamVectorUncheckedCreateWithoutTeamInput>
}

export type TeamVectorUpsertWithoutTeamInput = {
  update: Prisma.XOR<Prisma.TeamVectorUpdateWithoutTeamInput, Prisma.TeamVectorUncheckedUpdateWithoutTeamInput>
  create: Prisma.XOR<Prisma.TeamVectorCreateWithoutTeamInput, Prisma.TeamVectorUncheckedCreateWithoutTeamInput>
  where?: Prisma.TeamVectorWhereInput
}

export type TeamVectorUpdateToOneWithWhereWithoutTeamInput = {
  where?: Prisma.TeamVectorWhereInput
  data: Prisma.XOR<Prisma.TeamVectorUpdateWithoutTeamInput, Prisma.TeamVectorUncheckedUpdateWithoutTeamInput>
}

export type TeamVectorUpdateWithoutTeamInput = {
  vector_json?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type TeamVectorUncheckedUpdateWithoutTeamInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  vector_json?: Prisma.StringFieldUpdateOperationsInput | string
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type TeamVectorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  team_id?: boolean
  vector_json?: boolean
  created_at?: boolean
  updated_at?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamVector"]>

export type TeamVectorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  team_id?: boolean
  vector_json?: boolean
  created_at?: boolean
  updated_at?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamVector"]>

export type TeamVectorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  team_id?: boolean
  vector_json?: boolean
  created_at?: boolean
  updated_at?: boolean
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}, ExtArgs["result"]["teamVector"]>

export type TeamVectorSelectScalar = {
  id?: boolean
  team_id?: boolean
  vector_json?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type TeamVectorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "team_id" | "vector_json" | "created_at" | "updated_at", ExtArgs["result"]["teamVector"]>
export type TeamVectorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}
export type TeamVectorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}
export type TeamVectorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  team?: boolean | Prisma.TeamDefaultArgs<ExtArgs>
}

export type $TeamVectorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TeamVector"
  objects: {
    team: Prisma.$TeamPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    team_id: number
    vector_json: string
    created_at: Date
    updated_at: Date
  }, ExtArgs["result"]["teamVector"]>
  composites: {}
}

export type TeamVectorGetPayload<S extends boolean | null | undefined | TeamVectorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload, S>

export type TeamVectorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TeamVectorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TeamVectorCountAggregateInputType | true
  }

export interface TeamVectorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TeamVector'], meta: { name: 'TeamVector' } }
  /**
   * Find zero or one TeamVector that matches the filter.
   * @param {TeamVectorFindUniqueArgs} args - Arguments to find a TeamVector
   * @example
   * // Get one TeamVector
   * const teamVector = await prisma.teamVector.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TeamVectorFindUniqueArgs>(args: Prisma.SelectSubset<T, TeamVectorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TeamVectorClient<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TeamVector that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TeamVectorFindUniqueOrThrowArgs} args - Arguments to find a TeamVector
   * @example
   * // Get one TeamVector
   * const teamVector = await prisma.teamVector.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TeamVectorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TeamVectorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TeamVectorClient<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TeamVector that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamVectorFindFirstArgs} args - Arguments to find a TeamVector
   * @example
   * // Get one TeamVector
   * const teamVector = await prisma.teamVector.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TeamVectorFindFirstArgs>(args?: Prisma.SelectSubset<T, TeamVectorFindFirstArgs<ExtArgs>>): Prisma.Prisma__TeamVectorClient<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TeamVector that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamVectorFindFirstOrThrowArgs} args - Arguments to find a TeamVector
   * @example
   * // Get one TeamVector
   * const teamVector = await prisma.teamVector.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TeamVectorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TeamVectorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TeamVectorClient<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TeamVectors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamVectorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TeamVectors
   * const teamVectors = await prisma.teamVector.findMany()
   * 
   * // Get first 10 TeamVectors
   * const teamVectors = await prisma.teamVector.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const teamVectorWithIdOnly = await prisma.teamVector.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends TeamVectorFindManyArgs>(args?: Prisma.SelectSubset<T, TeamVectorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TeamVector.
   * @param {TeamVectorCreateArgs} args - Arguments to create a TeamVector.
   * @example
   * // Create one TeamVector
   * const TeamVector = await prisma.teamVector.create({
   *   data: {
   *     // ... data to create a TeamVector
   *   }
   * })
   * 
   */
  create<T extends TeamVectorCreateArgs>(args: Prisma.SelectSubset<T, TeamVectorCreateArgs<ExtArgs>>): Prisma.Prisma__TeamVectorClient<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TeamVectors.
   * @param {TeamVectorCreateManyArgs} args - Arguments to create many TeamVectors.
   * @example
   * // Create many TeamVectors
   * const teamVector = await prisma.teamVector.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TeamVectorCreateManyArgs>(args?: Prisma.SelectSubset<T, TeamVectorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TeamVectors and returns the data saved in the database.
   * @param {TeamVectorCreateManyAndReturnArgs} args - Arguments to create many TeamVectors.
   * @example
   * // Create many TeamVectors
   * const teamVector = await prisma.teamVector.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TeamVectors and only return the `id`
   * const teamVectorWithIdOnly = await prisma.teamVector.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TeamVectorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TeamVectorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TeamVector.
   * @param {TeamVectorDeleteArgs} args - Arguments to delete one TeamVector.
   * @example
   * // Delete one TeamVector
   * const TeamVector = await prisma.teamVector.delete({
   *   where: {
   *     // ... filter to delete one TeamVector
   *   }
   * })
   * 
   */
  delete<T extends TeamVectorDeleteArgs>(args: Prisma.SelectSubset<T, TeamVectorDeleteArgs<ExtArgs>>): Prisma.Prisma__TeamVectorClient<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TeamVector.
   * @param {TeamVectorUpdateArgs} args - Arguments to update one TeamVector.
   * @example
   * // Update one TeamVector
   * const teamVector = await prisma.teamVector.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TeamVectorUpdateArgs>(args: Prisma.SelectSubset<T, TeamVectorUpdateArgs<ExtArgs>>): Prisma.Prisma__TeamVectorClient<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TeamVectors.
   * @param {TeamVectorDeleteManyArgs} args - Arguments to filter TeamVectors to delete.
   * @example
   * // Delete a few TeamVectors
   * const { count } = await prisma.teamVector.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TeamVectorDeleteManyArgs>(args?: Prisma.SelectSubset<T, TeamVectorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TeamVectors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamVectorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TeamVectors
   * const teamVector = await prisma.teamVector.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TeamVectorUpdateManyArgs>(args: Prisma.SelectSubset<T, TeamVectorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TeamVectors and returns the data updated in the database.
   * @param {TeamVectorUpdateManyAndReturnArgs} args - Arguments to update many TeamVectors.
   * @example
   * // Update many TeamVectors
   * const teamVector = await prisma.teamVector.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TeamVectors and only return the `id`
   * const teamVectorWithIdOnly = await prisma.teamVector.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TeamVectorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TeamVectorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TeamVector.
   * @param {TeamVectorUpsertArgs} args - Arguments to update or create a TeamVector.
   * @example
   * // Update or create a TeamVector
   * const teamVector = await prisma.teamVector.upsert({
   *   create: {
   *     // ... data to create a TeamVector
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TeamVector we want to update
   *   }
   * })
   */
  upsert<T extends TeamVectorUpsertArgs>(args: Prisma.SelectSubset<T, TeamVectorUpsertArgs<ExtArgs>>): Prisma.Prisma__TeamVectorClient<runtime.Types.Result.GetResult<Prisma.$TeamVectorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TeamVectors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamVectorCountArgs} args - Arguments to filter TeamVectors to count.
   * @example
   * // Count the number of TeamVectors
   * const count = await prisma.teamVector.count({
   *   where: {
   *     // ... the filter for the TeamVectors we want to count
   *   }
   * })
  **/
  count<T extends TeamVectorCountArgs>(
    args?: Prisma.Subset<T, TeamVectorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TeamVectorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TeamVector.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamVectorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TeamVectorAggregateArgs>(args: Prisma.Subset<T, TeamVectorAggregateArgs>): Prisma.PrismaPromise<GetTeamVectorAggregateType<T>>

  /**
   * Group by TeamVector.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TeamVectorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TeamVectorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TeamVectorGroupByArgs['orderBy'] }
      : { orderBy?: TeamVectorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TeamVectorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTeamVectorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TeamVector model
 */
readonly fields: TeamVectorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TeamVector.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TeamVectorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  team<T extends Prisma.TeamDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TeamDefaultArgs<ExtArgs>>): Prisma.Prisma__TeamClient<runtime.Types.Result.GetResult<Prisma.$TeamPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TeamVector model
 */
export interface TeamVectorFieldRefs {
  readonly id: Prisma.FieldRef<"TeamVector", 'Int'>
  readonly team_id: Prisma.FieldRef<"TeamVector", 'Int'>
  readonly vector_json: Prisma.FieldRef<"TeamVector", 'String'>
  readonly created_at: Prisma.FieldRef<"TeamVector", 'DateTime'>
  readonly updated_at: Prisma.FieldRef<"TeamVector", 'DateTime'>
}
    

// Custom InputTypes
/**
 * TeamVector findUnique
 */
export type TeamVectorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorInclude<ExtArgs> | null
  /**
   * Filter, which TeamVector to fetch.
   */
  where: Prisma.TeamVectorWhereUniqueInput
}

/**
 * TeamVector findUniqueOrThrow
 */
export type TeamVectorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorInclude<ExtArgs> | null
  /**
   * Filter, which TeamVector to fetch.
   */
  where: Prisma.TeamVectorWhereUniqueInput
}

/**
 * TeamVector findFirst
 */
export type TeamVectorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorInclude<ExtArgs> | null
  /**
   * Filter, which TeamVector to fetch.
   */
  where?: Prisma.TeamVectorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamVectors to fetch.
   */
  orderBy?: Prisma.TeamVectorOrderByWithRelationInput | Prisma.TeamVectorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TeamVectors.
   */
  cursor?: Prisma.TeamVectorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamVectors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamVectors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TeamVectors.
   */
  distinct?: Prisma.TeamVectorScalarFieldEnum | Prisma.TeamVectorScalarFieldEnum[]
}

/**
 * TeamVector findFirstOrThrow
 */
export type TeamVectorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorInclude<ExtArgs> | null
  /**
   * Filter, which TeamVector to fetch.
   */
  where?: Prisma.TeamVectorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamVectors to fetch.
   */
  orderBy?: Prisma.TeamVectorOrderByWithRelationInput | Prisma.TeamVectorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TeamVectors.
   */
  cursor?: Prisma.TeamVectorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamVectors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamVectors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TeamVectors.
   */
  distinct?: Prisma.TeamVectorScalarFieldEnum | Prisma.TeamVectorScalarFieldEnum[]
}

/**
 * TeamVector findMany
 */
export type TeamVectorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorInclude<ExtArgs> | null
  /**
   * Filter, which TeamVectors to fetch.
   */
  where?: Prisma.TeamVectorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TeamVectors to fetch.
   */
  orderBy?: Prisma.TeamVectorOrderByWithRelationInput | Prisma.TeamVectorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TeamVectors.
   */
  cursor?: Prisma.TeamVectorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TeamVectors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TeamVectors.
   */
  skip?: number
  distinct?: Prisma.TeamVectorScalarFieldEnum | Prisma.TeamVectorScalarFieldEnum[]
}

/**
 * TeamVector create
 */
export type TeamVectorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorInclude<ExtArgs> | null
  /**
   * The data needed to create a TeamVector.
   */
  data: Prisma.XOR<Prisma.TeamVectorCreateInput, Prisma.TeamVectorUncheckedCreateInput>
}

/**
 * TeamVector createMany
 */
export type TeamVectorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TeamVectors.
   */
  data: Prisma.TeamVectorCreateManyInput | Prisma.TeamVectorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TeamVector createManyAndReturn
 */
export type TeamVectorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * The data used to create many TeamVectors.
   */
  data: Prisma.TeamVectorCreateManyInput | Prisma.TeamVectorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TeamVector update
 */
export type TeamVectorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorInclude<ExtArgs> | null
  /**
   * The data needed to update a TeamVector.
   */
  data: Prisma.XOR<Prisma.TeamVectorUpdateInput, Prisma.TeamVectorUncheckedUpdateInput>
  /**
   * Choose, which TeamVector to update.
   */
  where: Prisma.TeamVectorWhereUniqueInput
}

/**
 * TeamVector updateMany
 */
export type TeamVectorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TeamVectors.
   */
  data: Prisma.XOR<Prisma.TeamVectorUpdateManyMutationInput, Prisma.TeamVectorUncheckedUpdateManyInput>
  /**
   * Filter which TeamVectors to update
   */
  where?: Prisma.TeamVectorWhereInput
  /**
   * Limit how many TeamVectors to update.
   */
  limit?: number
}

/**
 * TeamVector updateManyAndReturn
 */
export type TeamVectorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * The data used to update TeamVectors.
   */
  data: Prisma.XOR<Prisma.TeamVectorUpdateManyMutationInput, Prisma.TeamVectorUncheckedUpdateManyInput>
  /**
   * Filter which TeamVectors to update
   */
  where?: Prisma.TeamVectorWhereInput
  /**
   * Limit how many TeamVectors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TeamVector upsert
 */
export type TeamVectorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorInclude<ExtArgs> | null
  /**
   * The filter to search for the TeamVector to update in case it exists.
   */
  where: Prisma.TeamVectorWhereUniqueInput
  /**
   * In case the TeamVector found by the `where` argument doesn't exist, create a new TeamVector with this data.
   */
  create: Prisma.XOR<Prisma.TeamVectorCreateInput, Prisma.TeamVectorUncheckedCreateInput>
  /**
   * In case the TeamVector was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TeamVectorUpdateInput, Prisma.TeamVectorUncheckedUpdateInput>
}

/**
 * TeamVector delete
 */
export type TeamVectorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorInclude<ExtArgs> | null
  /**
   * Filter which TeamVector to delete.
   */
  where: Prisma.TeamVectorWhereUniqueInput
}

/**
 * TeamVector deleteMany
 */
export type TeamVectorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TeamVectors to delete
   */
  where?: Prisma.TeamVectorWhereInput
  /**
   * Limit how many TeamVectors to delete.
   */
  limit?: number
}

/**
 * TeamVector without action
 */
export type TeamVectorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TeamVector
   */
  select?: Prisma.TeamVectorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TeamVector
   */
  omit?: Prisma.TeamVectorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TeamVectorInclude<ExtArgs> | null
}
